GET-endpoints for issues by status/description/summary
edu-xored/tracker-web pull request #10
Opened 2016-10-25 15:52 UTC by pleshkovvli

2016-10-25 16:15 UTC, pleshkovvli commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как разработчик фронтенда, хочу GET-эндпойнт для тасок по статусу/описанию.](https://trello.com/c/zxKyACFL/31-get)

2016-10-25 16:18 UTC, kevromster requested changes

2016-10-25 16:18 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +import java.util.*;
лучше явно импортировать нужные зависимости, без *

2016-10-25 16:18 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +
лишняя пустая строка не нужна

2016-10-25 16:18 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +    public List<Issue> getIssuesByStatus(@RequestParam("status") Issue.Status status){
нет пробела перед скобкой {  - и везде ниже тоже

2016-10-25 16:18 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +            throw new IssueNotFoundStatusException();
А зачем? пусть пустой список возвращается

2016-10-25 16:18 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +    public List<Issue> getIssuesByDescription(@RequestParam("description") String description){
Что-то я не уверен в необходимости сейчас эндпойнтов по description и summary. Мне кажется, когда будем поиск реализовывать, там и придумаем как это лучше сделать. А пока я бы убрал.
@mgtriffid как думаешь?

2016-10-25 16:18 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +    @ResponseStatus(value = HttpStatus.NOT_FOUND, reason = "Status not found")
Соответственно, все эти эксепшны не нужны.

2016-10-25 16:18 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +
опять лишняя пустая строка

2016-10-26 03:41 UTC, pleshkovvli commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +
Вроде всё исправил

2016-10-26 04:34 UTC, kevromster requested changes
- нужно убедиться, что эндпойнт корректно работает

2016-10-26 04:34 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +}
добавить пустую строку в конце

2016-10-26 07:53 UTC, pleshkovvli commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +}
А как убедиться, что эндпоинт корректно работает??

2016-10-26 08:08 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +}
Сделать get-запрос из браузера и увидеть, что тебе пришёл валидный ответ - в данном случае списки объектов.
А вообще, рекомендую настроить и изучить postman для отладки любых типов запросов.

2016-10-26 08:08 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +}
Сделать get-запрос из браузера и увидеть, что тебе пришёл валидный ответ - в данном случае списки объектов.
А вообще, рекомендую настроить и изучить postman для отладки любых типов запросов.

2016-10-26 08:46 UTC, kevromster approved these changes

2016-10-26 08:47 UTC, merged

2016-10-26 08:58 UTC, pleshkovvli commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +}
Работает