Posting comment on issue
edu-xored/tracker-web pull request #12
Opened 2016-10-27 05:55 UTC by Declow0

Данная ветка добавляет пустой конструктор к Comment.java и вносит некоторые изменения в подрядок функций для корректной работы с JSON. Создан класс CommentController. Его end-point "/postcomment". Изменены в соответствии html и js файлы для постинга комментариев. Добавлена зависимость для работы с LocalDateTime как JSON.

Card: #28

2016-10-27 05:56 UTC, Declow0 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как разраб фронтенда, хочу эндпойнт для сущности "Комментарий", чтобы мой фронтенд мог POSTить комменты](https://trello.com/c/TWOA9zxz/28-post)

2016-10-27 07:57 UTC, mgtriffid requested changes

2016-10-27 07:57 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Comment.java
> +        createdDateTime = null;
А зачем здесь без `this`? Выглядит так, что можно и остальное без `this`. Или вообще унести в инициализацию.

2016-10-27 07:57 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Comment.java
> +        this.author = "";
А для чего `author` пустая строка? Почему бы не держать по умолчанию `null`? (это не призыв заменить, это призыв разъяснить)

2016-10-27 07:57 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/CommentController.java
> +@RestController
Как обсудили в чатике, будет лучше путь `/issues/{issueHash}/comments`

2016-10-27 07:57 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/CommentController.java
> +    @RequestMapping(value = "/postcomment", method = RequestMethod.POST)
Есть алиас `@PostMapping`, который являет собой `@RequestMapping` с методом POST. В других местах используем эти алиасы, давайте придерживаться этого по всему проекту.

2016-10-27 07:57 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/CommentController.java
> +    public void post(@RequestBody Comment comment, @RequestParam("issueHash") long issueHash) {
`@RequestParam` это же который после знака вопроса в URL? Давай лучше `@PathParam`, или как там в спринге.

2016-10-27 07:57 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/resources/static/js/postcomment.js
> +			headers :   {'Content-Type': 'application/json'}
А по умолчанию не ставит `Content-Type`? Вот зараза...

2016-10-27 07:57 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/resources/static/js/postcomment.js
> +        }
Тут какая-то печаль с выравниванием кода, где-то табы, где-то пробелы. Давай везде использовать что-то одно.

2016-10-27 07:57 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/resources/static/js/postcomment.js
> +	    if ($scope.comment.author == null) {
Может быть ещё `undefined` и пустая строка. Лучше `if (!$scope.comment.author)`.

2016-10-27 07:57 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Comment.java
> +        this.createdDateTime = LocalDateTime.now();
Вот это очень странно, что setter без параметра. Как тут поступить правильно - не знаю, но явно не так :) Сеттер это требование десериализации?

2016-10-27 07:57 UTC, mgtriffid commented on backend/tracker-web-app.backend/pom.xml
> +	<dependency>
Здесь тоже какая-то печаль с выравниванием. Отровняй плз всю pom'ку в едином стиле.

2016-10-27 08:55 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/resources/static/js/postcomment.js
> +	    if ($scope.comment.author == null) {
Спасибо, не знал что тут писать, ибо ничего не работало.

2016-10-27 09:05 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Comment.java
> +        this.author = "";
Done.

2016-10-27 09:05 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Comment.java
> +        createdDateTime = null;
Done.

2016-10-27 09:06 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Comment.java
> +        this.createdDateTime = LocalDateTime.now();
Done.

2016-10-27 09:06 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/CommentController.java
> +@RestController
Done.

2016-10-27 09:06 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/CommentController.java
> +    @RequestMapping(value = "/postcomment", method = RequestMethod.POST)
Done.

2016-10-27 09:06 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/CommentController.java
> +    public void post(@RequestBody Comment comment, @RequestParam("issueHash") long issueHash) {
Done.

2016-10-27 09:06 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/resources/static/js/postcomment.js
> +	    if ($scope.comment.author == null) {
Done.

2016-10-27 09:06 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/resources/static/js/postcomment.js
> +        }
Done.

2016-10-27 09:06 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/resources/static/js/postcomment.js
> +			headers :   {'Content-Type': 'application/json'}
Done.

2016-10-27 09:06 UTC, Declow0 commented on backend/tracker-web-app.backend/pom.xml
> +	<dependency>
Done.

2016-10-27 13:25 UTC, kevromster requested changes

2016-10-27 13:25 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Comment.java
> +    public Comment() {
Нам точно нужен пустой конструктор?
Если даже да - приравнивать к null каждое поле класса в нём не нужно, это автоматически делается.

2016-10-27 13:25 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Comment.java
> +        createdDateTime = null;
предлагаю now() - что такое нулевая дата?

2016-10-27 13:25 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Comment.java
> -    public String getAuthor() {
Переколбашены методы - ок, пусть будет, но тут стоит учитывать возможные проблемы мёрджа этой ветки с другими изменениями. Такие переколбасы стоит делать только когда они действительно нужны и полезны.

2016-10-27 13:25 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Comment.java
> +}
пустая строка в конце файла

2016-10-27 13:25 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/resources/static/js/postcomment.js
> +			url	:	'/issues/'+$scope.issueHash+'/comments',
операторы лучше пробелами отделять: x + y вместо x+y

2016-10-27 13:25 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/resources/static/js/postcomment.js
>  });
пустая строка в конце файла

2016-10-27 13:34 UTC, mgtriffid requested changes

2016-10-27 13:34 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/CommentController.java
> +    @PostMapping(value = "/issues/{issueHash}/comments")
Этот путь будет общим для комментов, так что его можно повешать на класс, а на методы потом будем вешать просто хвостики пути, типа `/{hash}`.

2016-10-27 18:14 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Comment.java
> +    public Comment() {
Да, для @RequestBody необходим. Ну вообще, да по спецификации Java все не инициализированные поле равны null.

2016-10-27 18:18 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Comment.java
> +        createdDateTime = null;
Не инициализированная, но now() установлю.

2016-10-27 18:42 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Comment.java
> +    public Comment() {
Done.

2016-10-27 18:43 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Comment.java
> +        createdDateTime = null;
Done. Так же это помогает полям не инициализированным в JSON, инициализироваться по данному конструктору.

2016-10-27 18:44 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Comment.java
> -    public String getAuthor() {
Я их делал, потому что с JSON проблемы были, но видимо зря. Done.

2016-10-27 18:44 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Comment.java
> +}
Done.

2016-10-27 18:44 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/resources/static/js/postcomment.js
> +			url	:	'/issues/'+$scope.issueHash+'/comments',
Done.

2016-10-27 18:45 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/resources/static/js/postcomment.js
>  });
Done.

2016-10-27 18:45 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/CommentController.java
> +    @PostMapping(value = "/issues/{issueHash}/comments")
Done. Путь указывается в @RestMapping.

2016-10-28 07:28 UTC, Declow0 commented
А можно пока не принимать pull request, поскольку хочется проверить возможность заполнять анонимного автора не в JS, а через конструктор без параметров.

2016-10-28 09:22 UTC, kevromster requested changes

2016-10-28 09:22 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/CommentController.java
> +        IssueController issueController = new IssueController();
стоп, мы тут зачем создаём объект _IssueController_? Чтобы получить доступ до статической мапы? А откуда мы тут знаем, что там статическая мапа? Не, не пойдёт

2016-10-28 09:22 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/CommentController.java
> +        Issue issue = issueController.getIssue(hash);
а если нет такой ишуи, что произойдёт?

2016-10-28 09:22 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/resources/static/js/postcomment.js
> +			.success(function() {
тут зачем-то отступ увеличил, имхо некрасиво

2016-10-28 09:22 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/resources/static/js/postcomment.js
> +				$scope.status = 'Comment didn\'t poste.';
post вместо poste

2016-10-28 09:22 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/resources/static/js/postcomment.js
> +		if ($scope.issueHash == undefined) {
а какого типа тут будет реально issueHash? число 3 или строка '3'?

2016-10-28 12:13 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/resources/static/js/postcomment.js
> +		if ($scope.issueHash == undefined) {
В html файле явно прописано type="number". Строки быть не может, поскольку в итоге должно быть поле формата long. А поскольку hash может быть равен 0, так и написал. так как !0=1 и код считает, что есть ошибка.

2016-10-28 12:16 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/resources/static/js/postcomment.js
> +			.success(function() {
http://contribute.jquery.org/style-guide/js/
Этого требует официальный стиль Chained Method Calls.

Также можно найти именно для Angular: Defer Controller Logic to Services.
https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md

Просят избегать случаев, когда нет отступа.

2016-10-28 12:25 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/resources/static/js/postcomment.js
> +				$scope.status = 'Comment didn\'t poste.';
Done.

2016-10-28 12:26 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/CommentController.java
> +        Issue issue = issueController.getIssue(hash);
Ошибка 400/404 не помню точно, что его нет.

2016-10-28 13:22 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/CommentController.java
> +        IssueController issueController = new IssueController();
Сделал getIssue статик методом, больше ничего не придумал пока. Done.

2016-10-29 12:14 UTC, kevromster requested changes

2016-10-29 12:14 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +    public static Issue getIssue(@PathVariable("hash") long hash) {
_static_ не пойдёт - тут либо выносить хранилище ишуёв в отдельный сервис, либо то, что я предложил в _CommentController_

2016-10-29 12:14 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/CommentController.java
> +    public void postComment(@RequestBody Comment comment, @PathVariable("issueHash") long hash) {
Что-то не соображу, а зачем нам сейчас вообще отдельный контроллер для комментов? В таком вот виде - почему этот _post_ не сделать частью _IssueController_? Чем добавление комментария тут отличается от обновления дескрипшна ишуя? Тогда и со статическим доступом к хранилищу проблем не будет.

2016-10-29 12:14 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/resources/static/js/postcomment.js
> +		if ($scope.issueHash == undefined) {
Вообще, в javascript всё очень хитро с проверками на undefined. Может, здесь и ок, не знаю, но погугли на тему javascript check for undefined. Возможно, @mgtriffid тут больше скажет.

2016-10-29 13:49 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +    public static Issue getIssue(@PathVariable("hash") long hash) {
Больше не static, done.

2016-10-29 13:50 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/CommentController.java
> +    public void postComment(@RequestBody Comment comment, @PathVariable("issueHash") long hash) {
PostComment теперь часть IsssueController. Done

2016-10-29 15:05 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/resources/static/js/postcomment.js
> +			.success(function() {
Имхо норм с отступами

2016-10-29 16:05 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/resources/static/js/postcomment.js
> +		if ($scope.issueHash == undefined) {
http://www.codereadability.com/how-to-check-for-undefined-in-javascript/
Вот, что я нашел. Короче написано правильно, но если будет браузер IE 8 или старше, то вроде не сработает. Но данное написание удовлетворяет стандарту ECMAScript 5 2009 года.

2016-10-30 03:18 UTC, kevromster requested changes

2016-10-30 03:18 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Comment.java
> +        author = "Anonymous";
можно сэкономить код, позвав тут this("Anonymous", null);

2016-10-30 03:18 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +        Issue issue = issueMap.get(hash);
а если такого ишуя нет? вернётся null, и в строке ниже будет NPE

2016-10-30 03:18 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/resources/static/js/postcomment.js
> +		if ($scope.issueHash == undefined) {
ok

2016-10-30 03:18 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/resources/static/js/postcomment.js
> +			.success(function() {
ok

2016-10-30 11:19 UTC, kevromster requested changes

2016-10-30 11:19 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +        issue.addComment(comment);
нужна проверка на null

2016-10-30 18:13 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +        Issue issue = issueMap.get(hash);
Done.

2016-10-30 18:13 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Comment.java
> +        author = "Anonymous";
Done.

2016-10-31 07:14 UTC, kevromster approved these changes
LGTM

2016-11-01 02:27 UTC, mgtriffid approved these changes
Мержабельно.

2016-11-01 02:27 UTC, merged