Обращение к /issues без параметра (Bug/37)
edu-xored/tracker-web pull request #14
Opened 2016-10-27 12:56 UTC by Astronautr

Добавил возможность отправляя GET-запрос по адресу localhost:8080/issues получать список всех `Issue`, находящихся в `issueMap`.

2016-10-27 12:56 UTC, Astronautr commented
![](https://github.trello.services/images/mini-trello-icon.png) [В IssueController (getIssuesByStatus) учесть ситуацию когда параметр запроса не подаётся.](https://trello.com/c/n8syjCDc/37-issuecontroller-getissuesbystatus)

2016-10-27 13:27 UTC, mgtriffid requested changes

2016-10-27 13:27 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +        for (Map.Entry<Long, Issue> entry : issueMap.entrySet()) {
У нас есть Java 8, давай через Stream API?

2016-10-27 15:21 UTC, kevromster requested changes

2016-10-27 15:21 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +import java.util.*;
писал уже, звёздочки - bad style

2016-10-27 15:21 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +            issueList = new ArrayList<Issue>(issueMap.values());
А вот вопрос, зачем мы _List_ возвращаем тут? Никакого порядка мы не гарантируем.
Тогда тут просто можно было бы _issueMap.values()_ вернуть

2016-10-27 15:21 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +        issueMap.entrySet()
можно сразу фильтровать issueMap.values(), зачем нам entry set'ы

2016-10-27 15:21 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +                .forEach(entry -> issueList.add(entry.getValue()));
ну и тут какой-нибудь _.collect(Collectors.toList())_

2016-10-28 04:03 UTC, Astronautr commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +        for (Map.Entry<Long, Issue> entry : issueMap.entrySet()) {
Done.

2016-10-28 04:03 UTC, Astronautr commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +import java.util.*;
Done.

2016-10-28 04:03 UTC, Astronautr commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +            issueList = new ArrayList<Issue>(issueMap.values());
Done.

2016-10-28 04:03 UTC, astronautr commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +        issueMap.entrySet()
Done.

2016-10-28 04:03 UTC, Astronautr commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +                .forEach(entry -> issueList.add(entry.getValue()));
Done.

2016-10-29 11:57 UTC, kevromster approved these changes
Теперь красота! :)

2016-10-29 14:56 UTC, mgtriffid approved these changes

2016-10-29 14:56 UTC, merged