Add Travis CI config file (Feature/12)
edu-xored/tracker-web pull request #15
Opened 2016-10-27 14:05 UTC by zaNudda

Добавлен файл конфигурации для Travis CI

Card: #12

2016-10-27 14:11 UTC, zaNudda commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как разраб, хочу CI, CD и автодеплой на какой-то бесплатный хостинг](https://trello.com/c/YsbKYn9G/12-ci-cd)

2016-10-27 15:44 UTC, kevromster requested changes
Что-то мне говорит, что этот файл должен быть в корне проекта. Билды travis на этот пулл-реквест сейчас не проходят.

2016-10-27 15:45 UTC, kevromster commented
Да, и commit messages вида "Update .travis.yml" непонятны

2016-10-27 15:49 UTC, zaNudda commented
@kevromster, ну он же в корне и есть? Или я как-то не так смотрю?
Билды я вижу что не проходят. Судя по heartbeat'у Travis'а у них были проблемы, что сейчас не так — ума не приложу.

> Да, и commit messages вида "Update .travis.yml" непонятны
Да это исключительно тестовые коммиты, их вообще удалить можно будет.

2016-10-30 15:10 UTC, zaNudda commented
Господа @kevromster, @mgtriffid, прошу или заапрувить ветку или кинуть инструкцией как править комментарии к коммитам или даже слиять оные (ну или может быть есть иной способ, как избавиться в этой ветке от всех ненужных коммитов и оставить только нужные).

2016-10-31 04:56 UTC, Astronautr commented
@zaNudda Могу посоветовать как править коммиты: для исправления последнего коммита достаточно в директории проекта выполнить `git commit --amend`. Результат - откроется редактор с текстом сообщения к последнему коммиту, который можно изменить. Если нужно изменить не последний коммит, а коммит номер N с конца, то нужно выполнить `git rebase -i HEAD~N`, откроется текстовый файл с метокой команды (по умолчанию стоит pick), скоращённым хешем, subject'ами каждого коммита. Для нужного коммита достаточно поменять pick на reword у коммитов, сообещние к которым хочешь поменять, закрыть окно текстового редактора, а в новом, открывшемся (что сделает сам гит), приступить к редактированию.

2016-10-31 06:43 UTC, kevromster requested changes

2016-10-31 06:43 UTC, kevromster commented on build.gradle
> +apply plugin:'java'
Мы же maven используем для сборки, а не gradle. Я предлагаю всё через мавен делать. Можно посмотреть, как настроена интеграция с Travis в других проектах - например edu-xored/memorise - у них всё работает через mvn.

2016-10-31 06:48 UTC, kevromster commented
@Astronautr @zaNudda верно, можно через git rebase. Только после этого git push сругается о том, что нельзя запушить изменения в гитхаб - ветка, так сказать, изменила направление и отросла в другую сторону. Пуш таких веток называется force push, и обычно это запрещено на уровне политики репозитория.
Я рекомендую удалить вообще текущую ветку из гитхаба и сделать новую, с чистыми правильными коммитами.

2016-10-31 06:52 UTC, kevromster requested changes

2016-10-31 06:52 UTC, kevromster commented on build.gradle
> +apply plugin:'java'
Видимо, правильный ответ здесь - переместить `pom.xml` из `tracker-web-app.backend/` в корень проекта

2016-10-31 06:57 UTC, kevromster commented on build.gradle
> +apply plugin:'java'
хм, да и вообще весь `src/` надо вытащить в корень, а о `backend/tracker-web-app.backend/` забыть

2016-10-31 15:02 UTC, closed without merging