Как разраб фронтенда, хочу CRUD эндпойнты для Issues (Feature/34)
edu-xored/tracker-web pull request #16
Opened 2016-10-27 14:21 UTC by whyme7

Реализованы запросы: POST, PUT, DELETE, PATCH. Для корректной работы @RequestBody потребовался конструктор без параметров у Issue.

2016-10-28 04:59 UTC, Astronautr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как разраб фронтенда, хочу CRUD эндпойнты для Issues, чтобы можно было запросами POST создавать новую Issue, PUT обновлять существующую, DELETE удалять, PATCH обновлять существующую частично](https://trello.com/c/fuzJm0Gl/34-crud-issues-post-issue-put-delete-patch)

2016-10-29 11:55 UTC, kevromster requested changes

2016-10-29 11:55 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> -        return Collections.unmodifiableList(comments);
а зачем unmodifiable убрал?

2016-10-29 11:55 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +        issue.setHash(issueCounter);
зачем тебе _issueCounter_, у тебя же есть _issueMap.size()_

2016-10-29 11:55 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +        issue.addComments(comments);
1) А _issue.setHash(hash)_ не нужно сделать?
2) Мы тут делаем _addComments_ вместо какого-нибудь _setComments_. Сейчас, наверное, это неважно (пока вопрос хранения комментов в ишуях или вне их не решён окончательно), но вообще потенциально нехорошее место.

2016-10-29 11:55 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +        if (issueMap.get(hash) == null) {
почему не _containsKey()_?

2016-10-29 11:55 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +            issue.getComments().addAll(patchedIssue.getComments());
_Issue.addComments()_ же есть

2016-10-29 11:55 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +        if (patchedIssue.getSummary() != null) {
А почему бы не сделать в самом классе _Issue_ метод `Issue updateIssue(Issue other) { /*...*/ return this; }`, куда всё это прописать?
Чем сейчас плохо - если кто-то добавить в _Issue_ новое поле, он наверняка забудет в этом методе добавить ещё один if'чик. А внутри _Issue_ - скорее всего не забудет.

2016-10-29 12:45 UTC, whyme7 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> -        return Collections.unmodifiableList(comments);
Если реализовывать возможность добавлять комменты через PATCH, то unmodifiable. Убираем и пусть этим занимается POST для комментов?

2016-10-29 12:57 UTC, whyme7 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> -        return Collections.unmodifiableList(comments);
Когда поменял issue.getComments().addAll(patchedIssue.getComments()); на issue.addComments(patchedIssue.getComments()); всё решилось. Патчем можно добавить коммент и с unmodifiable.

2016-10-29 13:17 UTC, artsaban commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> -        return Collections.unmodifiableList(comments);
Done.

2016-10-29 13:18 UTC, whyme7 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +        issue.setHash(issueCounter);
Done.

2016-10-29 13:18 UTC, whyme7 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +        issue.addComments(comments);
Да, действительно пропустил момент с hash. Done.

2016-10-29 13:18 UTC, artsaban commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +        if (issueMap.get(hash) == null) {
Done.

2016-10-29 13:18 UTC, whyme7 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +        if (patchedIssue.getSummary() != null) {
Done.

2016-10-29 13:18 UTC, whyme7 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +            issue.getComments().addAll(patchedIssue.getComments());
Done.

2016-10-29 15:00 UTC, mgtriffid approved these changes

2016-10-30 02:48 UTC, kevromster approved these changes

2016-10-30 02:48 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +            this.setSummary(other.getSummary());
_this._ тут мне кажется излишним, ну да ладно

2016-10-30 02:48 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +        return issue;
можно было просто написать `return issue.updateIssue(..);`

2016-10-30 04:42 UTC, whyme7 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +            this.setSummary(other.getSummary());
Done.

2016-10-30 04:42 UTC, whyme7 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/IssueController.java
> +        return issue;
Done.

2016-10-30 08:12 UTC, merged