Feature/38: Как разраб фронтенда, хочу каркас роутинга
edu-xored/tracker-web pull request #18
Opened 2016-10-29 17:34 UTC by mgtriffid

Чтобы проверить, надо открыть /html/routingExample.html и покликать.
Клики "назад" и "вперёд" работают, refresh пока нет. Потом надо сделать.

2016-10-29 17:35 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/resources/static/html/routingExample.html
> +    <base href="/html">
Это нужно (кажется) потому, что это не index.html. Потом переедет в index.html, и мб от этого мы избавимся.

2016-10-29 17:36 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/resources/static/js/routingApp.js
> +        $locationProvider.html5Mode(true);
Это чтобы работал `<base>` тэг

2016-10-29 17:38 UTC, mgtriffid commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как разраб фронтенда, хочу каркас роутинга](https://trello.com/c/UbySKAHF/38--)

2016-10-30 03:01 UTC, kevromster requested changes

2016-10-30 03:01 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/resources/static/html/routingExample.html
> +</html>
во всех файлах нужна пустая строка в конце

2016-10-31 01:08 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/resources/static/html/routingExample.html
> +</html>
Done in a1ad3fc7af038dc0edf3dc716274ea84ee5f1e90

2016-10-31 07:06 UTC, kevromster approved these changes

2016-10-31 07:34 UTC, merged