Как пользователь, хочу на одной странице видеть сразу все таски (Feature/4)
edu-xored/tracker-web pull request #19
Opened 2016-10-30 03:12 UTC by Astronautr

2016-10-30 03:12 UTC, Astronautr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как пользователь, хочу на одной странице видеть сразу все имеющиеся таски во всех статусах](https://trello.com/c/GqEBFOOg/4--)

2016-10-31 07:11 UTC, kevromster requested changes

2016-10-31 07:11 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +    @JsonIgnore
предлагаю отделить пустой строкой сверху

2016-10-31 07:11 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/resources/static/html/allissues.html
> +<script src="../js/allissues.js"></script>
1) относительные пути? `/js/allissues.js`
2) может всё-таки `allIssues` - чтобы не в одном регистре?

2016-10-31 07:11 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/resources/static/js/allissues.js
> +      $http.get('http://localhost:8080/issues').
хардкод `localhost:8080`

2016-10-31 07:57 UTC, Astronautr commented on backend/tracker-web-app.backend/src/main/resources/static/js/allissues.js
> +      $http.get('http://localhost:8080/issues').
Done.

2016-10-31 07:57 UTC, Astronautr commented on backend/tracker-web-app.backend/src/main/resources/static/html/allissues.html
> +<script src="../js/allissues.js"></script>
Done.

2016-10-31 07:57 UTC, astronautr commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +    @JsonIgnore
Done.

2016-10-31 08:33 UTC, kevromster approved these changes
LGTM

2016-11-01 02:28 UTC, mgtriffid approved these changes

2016-11-01 02:28 UTC, merged