Feature/3
edu-xored/tracker-web pull request #2
Opened 2016-10-21 05:29 UTC by Astronautr

2016-10-21 05:29 UTC, Astronautr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как пользователь, хочу уметь запускать web-приложение в одну команду на локальной машине](https://trello.com/c/Jzl8aMFu/3-web)

2016-10-21 07:56 UTC, kevromster requested changes

2016-10-21 07:56 UTC, kevromster commented on tracker-web-app-start.sh
> +
В начале скрипта нужно комментарий-описание, что он делает.

2016-10-21 07:56 UTC, kevromster commented on tracker-web-app-start.sh
> +echo "Server started"
Написали started, а запускать ещё и не пробовали. Здесь можно "starting..." написать, а "started" - после успешного запуска

2016-10-21 07:56 UTC, kevromster commented on tracker-web-app-start.sh
> +echo -e "\nServer started\n" >> tracker-web-app.log
давай имя лог-файла в переменную положим, чтобы менять легко было

2016-10-21 07:56 UTC, kevromster commented on tracker-web-app-start.sh
> +
+здесь echo "Killing server..."

2016-10-21 07:56 UTC, kevromster commented on tracker-web-app-start.sh
> +do
тут без точки с запятой, а в if'е выше и в while ниже с точкой запятой. Давай единого стиля придерживаться - лучше с точкой с запятой

2016-10-21 07:56 UTC, kevromster commented on tracker-web-app-start.sh
> +while [[ $(ps | grep -o $PROC_ID) -eq "$PROC_ID" ]]; do
тут, кстати, копипаста кода - предлагаю вынести в отдельную функцию с говорящим названием

2016-10-21 07:56 UTC, kevromster commented on tracker-web-app-start.sh
> +exit 0
добавить endline

2016-10-21 07:59 UTC, kevromster commented
По коммит-мессаджам: ок, только точку после "Card: #XX" не надо, так как обычно на это коммит-хуки парсят

2016-10-21 08:00 UTC, Astronautr commented on tracker-web-app-start.sh
> +do
Ок, исправляюсь.

2016-10-21 08:08 UTC, kevromster commented on tracker-web-app-start.sh
> +java -jar $PATH_TO_JAR >> tracker-web-app.log &
стоит добавить 2>&1 перед >>, чтобы strerr не потерялся

2016-10-21 10:01 UTC, astronautr commented on tracker-web-app-start.sh
> +
Done.

2016-10-21 10:01 UTC, astronautr commented on tracker-web-app-start.sh
> +echo "Server started"
Исправил.

2016-10-21 10:02 UTC, Astronautr commented on tracker-web-app-start.sh
> +echo -e "\nServer started\n" >> tracker-web-app.log
Сделал.

2016-10-21 10:08 UTC, Astronautr commented on tracker-web-app-start.sh
> +do
Done.

2016-10-21 10:08 UTC, Astronautr commented on tracker-web-app-start.sh
> +
Done.

2016-10-21 10:08 UTC, Astronautr commented on tracker-web-app-start.sh
> +while [[ $(ps | grep -o $PROC_ID) -eq "$PROC_ID" ]]; do
Done.

2016-10-21 10:08 UTC, Astronautr commented on tracker-web-app-start.sh
> +exit 0
Done.

2016-10-21 10:29 UTC, kevromster requested changes

2016-10-21 10:29 UTC, kevromster commented on tracker-web-app-start.sh
> +java -jar $PATH_TO_JAR >> $LOG_FILE &
$PATH_TO_JAR лучше в кавычках для учёта пробелов. Плюс, писал ранее - добавить 2>&1 перед >>, чтобы stderr поток тоже в файл перенаправлялся

2016-10-21 10:29 UTC, kevromster commented on tracker-web-app-start.sh
> +if !(test -e $PATH_TO_JAR); then
тут тоже в кавычках

2016-10-21 10:29 UTC, kevromster commented on tracker-web-app-start.sh
> +checkServerIsAlive
Зачем тебе копипаст кода из while? инициализировать SERVER_ALIVE=0 и пусть в while'е чекает дальше

2016-10-21 12:14 UTC, Astronautr commented on tracker-web-app-start.sh
> +java -jar $PATH_TO_JAR >> $LOG_FILE &
Строковые переменные поместил в кавычки. 2>&1 >> у меня не сработало, зато &>> сделало своё дело (правда не до конца): лог сеанса спринга пишется в файл, а ошибки в стандартный вывод + в файл.

2016-10-21 12:14 UTC, Astronautr commented on tracker-web-app-start.sh
> +checkServerIsAlive
Done.

2016-10-21 12:19 UTC, Astronautr commented on tracker-web-app-start.sh
> +if !(test -e $PATH_TO_JAR); then
Done.

2016-10-21 12:30 UTC, Astronautr commented on tracker-web-app-start.sh
> +java -jar $PATH_TO_JAR >> tracker-web-app.log &
Done.

2016-10-21 14:57 UTC, kevromster commented on tracker-web-app-start.sh
> +java -jar $PATH_TO_JAR >> $LOG_FILE &
я вспоминаю, там правильный формат `echo 'text' >> file 2>&1`, но как у тебя получилось тоже ок.

2016-10-21 15:05 UTC, kevromster requested changes

2016-10-21 15:05 UTC, kevromster commented on tracker-web-app-start.bat
> +echo Starting server...
не запрещается разделять пустыми строками логические блоки кода :) Даже наоборот. Здесь, например, можно отделить, а то сейчас весь скрипт одной стеной выглядит

2016-10-21 15:05 UTC, kevromster commented on tracker-web-app-start.bat
> +set log=tracker-web-app.log
аналогично .sh-файлу - комментарий в начале скрипта, что тут делается

2016-10-21 15:05 UTC, kevromster commented on tracker-web-app-start.bat
> +:end
нужна пустая строка в конце - все файлы должны ею заканчиваться

2016-10-21 21:22 UTC, Declow0 commented on tracker-web-app-start.bat
> +set log=tracker-web-app.log
Done.

2016-10-21 21:22 UTC, Declow0 commented on tracker-web-app-start.bat
> +echo Starting server...
Done.

2016-10-21 21:23 UTC, Declow0 commented on tracker-web-app-start.bat
> +:end
Done, я надеюсь правильно понял, что под пустой строкой подразумевалось exit.

2016-10-22 05:01 UTC, astronautr reviewed
@Declow0 В коммите-месседже точно не стоит добавлять точку в конец subject и после "Card: #N" точка не нужна. Как сказали, такие мелочи нужно соблюдать дабы парсящие коммит-хуки смогли всё обработать. Кстати, фразу "Better version of code" можно было пояснить в теле запроса - было бы приятно сразу видеть что стало лучше просто прочитав сообщение к коммиту.

2016-10-22 05:14 UTC, Astronautr commented on tracker-web-app-start.bat
> +:end
@Declow0 Думаю, ты всё же неверно понял, а ввиду имелась необходимость вставки пустой строки в конце файла. По стандарту [POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206), строка, не оканчивающаяся символом перехода на другую строку таковой и не считается. Можешь почитать об этом на [Stack Overflow](http://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline).

2016-10-23 04:42 UTC, kevromster commented on tracker-web-app-start.bat
> +:end
@Astronautr  ага, верно )

2016-10-23 05:04 UTC, kevromster requested changes

2016-10-23 05:04 UTC, kevromster commented on tracker-web-app-start.bat
> +taskkill /fi "windowtitle eq tracker-web-app" /im cmd.exe >nul
вот это нигифа не надёжно, а если у меня несколько окон с таким названием? нужно как-то получить pid запущенного процесса и убивать его

2016-10-23 05:04 UTC, kevromster commented on tracker-web-app-start.bat
> +echo Press any button to quit
плюс где-то здесь echo Server started

2016-10-24 03:43 UTC, kevromster requested changes

2016-10-24 03:43 UTC, kevromster commented on get-cmd-pid.bat
> +endlocal & if "%~1" equ "" (echo(%PID%)>PID.tmp else set "%~1=%PID%"
1) тут со скобками всё в порядке? открывающих больше почему-то
2) PID.tmp - имя файла захардкожено в двух местах (ещё хуже - в двух разных скриптах). Лучше его передавать параметром в этот скрипт. А функционал вывода в stdout нам не нужен. Плюс поправь комментарий, чтобы он описывал это поведение. Да, и имя файла нужно по-хорошему генерировать в уникальным в temp-каталоге, аналогично тому, как здесь %lock% создаётся.
3) Уместить всё это в внутри одного start-скрипта не получилось? чтобы не плодить одноразовых utils-скриптов. Если с этим проблемы, то ок, пусть остаётся так.

2016-10-24 03:43 UTC, kevromster commented on tracker-web-app-start.bat
> +set TCP=TCP_ports.tmp
то же замечание к имени файла, что и PID.tmp - нужно его уникальным генерить где-нибудь в %temp%, ну или без промежуточных файлов обходиться

2016-10-24 12:06 UTC, Declow0 commented on get-cmd-pid.bat
> +endlocal & if "%~1" equ "" (echo(%PID%)>PID.tmp else set "%~1=%PID%"
Done.
1) Да все в порядке, пробовал добавлять все плохо. Скрипт был взят отсюда http://www.dostips.com/forum/viewtopic.php?p=38870#p38870
2) PID теперь имеет уникальное имя, передается как параметр
3) Нет не получилось, так как скрипт получает PID данного окна CMD. Сервер открывается в новом CMD окне, поэтому в нем нужно запустить этот скрипт, а писать код в вызове команды у меня не получилось, он не обрабатывает.

2016-10-24 12:07 UTC, Declow0 commented on tracker-web-app-start.bat
> +set TCP=TCP_ports.tmp
Done.
TCP так же как и PID создается в директории %temp% с уникальным именем.

2016-10-24 15:54 UTC, kevromster reviewed
Нужно подтверждение со сторонних Win-машин, что скрипт работает корректно. Тогда будет approve.

2016-10-25 03:44 UTC, Astronautr commented
@Declow0 При отсутствии в рабочей корневой директории (той, где находится скрипт) лог файла, информация в него не дописывается, т.к. файл попросту не найден "FINDSTR: Не удаётся открыть файл tracker-web-app.log". Нужно создавать файл при его отстутствии.

2016-10-25 05:42 UTC, kevromster approved these changes
LGTM

2016-10-25 09:42 UTC, merged