Подробная спецификация бизнес-сущности "Пользователь" (Doc/43)
edu-xored/tracker-web pull request #25
Opened 2016-11-03 23:23 UTC by Declow0

Первая версия модели пользователя, которая является максимально упрощенной.

Card: #43

2016-11-03 23:24 UTC, Declow0 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как разработчику, мне необходима подробная спецификация бизнес-сущности "Пользователь", для того чтобы её имплементировать](https://trello.com/c/tuMVLEGh/43--)

2016-11-04 04:02 UTC, kevromster requested changes

2016-11-04 04:02 UTC, kevromster commented on USER.md
> +Пользователь должен указать путь к данному файлу, поскольку интернет страница не имеет доступа к файлам операционной системы, а имеет доступ только к песочнице. Возможно поиск данного файла написать
Тут не соглашусь. Текущее имя и email для конкретного репозитория можно узнать, вызвав
`git config user.name`
`git config user.email`
Если нам это нужно знать на ui, значит должен быть endpoint на бэкенде, который вызывает эти команды и возвращает имя и почту.

2016-11-04 05:28 UTC, Declow0 commented on USER.md
> +Пользователь должен указать путь к данному файлу, поскольку интернет страница не имеет доступа к файлам операционной системы, а имеет доступ только к песочнице. Возможно поиск данного файла написать
То есть тогда мы забываем про возможность иметь уникальное имя пользователя для конкретного репозитория. Хорошо.

2016-11-04 06:05 UTC, kevromster approved these changes

2016-11-07 08:03 UTC, merged