Add pagination on all Issue page (feature/15)
edu-xored/tracker-web pull request #26
Opened 2016-11-04 03:10 UTC by Declow0

Реализована простейшая пагинация, с выбором элементов на странице.

Card: #15

2016-11-04 03:10 UTC, Declow0 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как пользователь, хочу пагинацию в табличке задач](https://trello.com/c/0ZvFtKBU/15--)

2016-11-04 04:09 UTC, kevromster requested changes

2016-11-04 04:09 UTC, kevromster commented on src/main/resources/static/controllers/allIssuesController.js
> +	.controller('issuesController', function($scope, $http) {
Здесь отступ почему-то лишний добавился.
Вообще, я вижу, что тут понамешаны отступы с табами и и пробелами - это нехорошо. Нужно выбрать что-то одно и всегда делать отступы одинаковым способом. Иначе будет каша.

2016-11-04 07:15 UTC, Astronautr commented
Нужно решить, хочется ли переходя назад от конкретного ишуя видеть таблицу, соответствующую пагинации установленной пользователем до перехода к этому ишую. И в рамках ли этой задачи сам вопрос.

2016-11-08 04:53 UTC, mgtriffid commented on src/main/resources/static/controllers/allIssuesController.js
> +    	$http.get('/issues').
Получается, у нас пагинация не правдишная, а виртуальная, да? Потому что мы всегда один фиг выгружаем всё и делаем пагинацию на клиенте, а не сервере. Настоящую будем делать потом?

2016-11-08 04:55 UTC, mgtriffid commented
Насчёт возврата на ту страницу, где был - мне кажется, по уму было бы сделать пагинацию так, что с какого issue показываем и сколько issue было бы в урле. И чтобы роутинг это разруливал. Тогда получим автоматически то, о чём говорит @Astronautr . Но да, давайте это не сейчас, потому что мы даже не знаем, как именно нам core команда даст пагинацию.

2016-11-09 13:28 UTC, Declow0 commented on src/main/resources/static/controllers/allIssuesController.js
> +	.controller('issuesController', function($scope, $http) {
Сейчас я все исправил, просто первое время GitHub считал, что у меня не 4 табуляция, а 8 и все ехало, пока на самом GitHub'е вручную не сделал.

2016-11-10 14:10 UTC, kevromster approved these changes
LGTM

2016-11-11 09:38 UTC, mgtriffid approved these changes
LGTM too.

2016-11-11 09:38 UTC, merged