Комментирование задач (Feature/26)
edu-xored/tracker-web pull request #29
Opened 2016-11-04 18:36 UTC by Astronautr

Добавил возможность комментировать задачи: простой переход по ссылке в каждом ишуе, к сделанной ранее форме комментария. За ненадобностью было удалено поле введения хеша комментируемого ишуя.

2016-11-04 18:36 UTC, Astronautr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как пользователь, хочу возможность комментировать задачи](https://trello.com/c/LZTt1R50/26--)

2016-11-07 07:57 UTC, kevromster requested changes

2016-11-07 07:57 UTC, kevromster commented on src/main/resources/static/controllers/postCommentController.js
> +				method	:	'POST',
тут и ниже табы после двоеточия? это неправильно совсем. Можно договориться принять табы для отступов (табы или пробелы использовать - должно быть прописано в style guide), но не для выравнивания в середине строки.

2016-11-07 08:53 UTC, Astronautr commented on src/main/resources/static/controllers/postCommentController.js
> +				method	:	'POST',
Ок. Учту, исправлю и запишу как **нельзя** использовать табы в style guide.

2016-11-07 13:58 UTC, kevromster approved these changes
LGTM

2016-11-08 02:36 UTC, Astronautr commented
Разобрался с конфликтами.

2016-11-08 05:09 UTC, mgtriffid commented on src/main/resources/static/index.html
> +    <script src="/controllers/postCommentController.js"></script>
А может лучше было бы в страничку конкретного issue встроить? Или это опять же на потом оставим пока что?

2016-11-08 11:52 UTC, kevromster commented on src/main/resources/static/index.html
> +    <script src="/controllers/postCommentController.js"></script>
Думаю, это лучше отдельной задачей, она, кажется, даже заведена.

2016-11-09 03:35 UTC, merged