Model User and simple controller(Feature/32)
edu-xored/tracker-web pull request #31
Opened 2016-11-04 20:09 UTC by Declow0

First realization of User model

Card: #32

2016-11-04 20:09 UTC, Declow0 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как разработчик фронтенда, хочу сущность "Пользователь", для того чтобы назначать на себя задачи, а также комментировать другие задачи под своим именем](https://trello.com/c/iJFr9vUm/32--)

2016-11-07 08:17 UTC, kevromster requested changes

2016-11-07 08:17 UTC, kevromster commented on src/main/java/edu/xored/tracker/User.java
> +        this(null, null);
этот _this()_ не нужен, т.к. не несёт никакой смысловой нагрузки

2016-11-07 08:17 UTC, kevromster commented on src/main/java/edu/xored/tracker/UserController.java
> +import java.io.*;
вместо звёздочек - явные импорты того, что необходимо

2016-11-07 08:17 UTC, kevromster commented on src/main/java/edu/xored/tracker/UserController.java
> +    private class InSrteamException extends RuntimeException {
Очепятка в имени класса. В целом - название не говорящее и завязанное на специфику места использования. Лучше придумать что-то другое.
reason тоже не очень написан - а если я там код изменю с readLine на что-то другое?

2016-11-07 08:17 UTC, kevromster commented on src/main/java/edu/xored/tracker/UserController.java
> +            theProcess = Runtime.getRuntime().exec("git config user.name");
1) Код получения theProcess здесь и ниже повторяется (со всеми try/catch). Копипаста зло, нужно выделить отдельный метод.
2) Имена команд "git config blabla..." лучше не хардкодить прямо тут, а вынести в отдельную private static final String константу класса.

2016-11-07 08:17 UTC, kevromster commented on src/main/java/edu/xored/tracker/UserController.java
> +            inStream = new BufferedReader(new InputStreamReader( theProcess.getInputStream() ));
1) тут бы лучше try-with-resources конструкцию применить, почитай про неё
2) опять же код для email ниже повторяется

2016-11-08 16:12 UTC, Declow0 commented on src/main/java/edu/xored/tracker/User.java
> +        this(null, null);
Изменен на конструктор без тела. Done.

2016-11-08 16:12 UTC, Declow0 commented on src/main/java/edu/xored/tracker/UserController.java
> +import java.io.*;
Done.

2016-11-08 16:14 UTC, Declow0 commented on src/main/java/edu/xored/tracker/UserController.java
> +            theProcess = Runtime.getRuntime().exec("git config user.name");
1) Создан метод getOutput().
2) А зачем final?  Ведь все инициализированные строки вроде по умолчанию final... Или я что-то неправильно понимаю...
Done.

2016-11-08 16:15 UTC, Declow0 commented on src/main/java/edu/xored/tracker/UserController.java
> +            inStream = new BufferedReader(new InputStreamReader( theProcess.getInputStream() ));
1) Реализовано. Узнал,что данная возможность появилась с появлением Java 7.
2) Исправлено выше.
Done.

2016-11-08 16:16 UTC, Declow0 commented on src/main/java/edu/xored/tracker/UserController.java
> +    private class InSrteamException extends RuntimeException {
Поменял на OutputException. Вроде говорящее и использовать можно не только тут. Ну и сделать комментарий TODO про Exceptions как говорили на митинге.
Done.

2016-11-09 09:29 UTC, kevromster requested changes

2016-11-09 09:29 UTC, kevromster commented on src/main/java/edu/xored/tracker/UserController.java
> +    private static String getNameCommand = "git config user.name";
здесь нужен `final` для того, чтобы нельзя было сделать так:
```
private void someMethod() {
  getNameCommand = "another command";
}
```

2016-11-09 09:29 UTC, kevromster commented on src/main/java/edu/xored/tracker/UserController.java
> +    String getOutput (String command) {
private?

2016-11-09 09:29 UTC, kevromster commented on src/main/java/edu/xored/tracker/UserController.java
> +        // TODO: How to work with exceptions? How to log them?
давай перенесём этот `TODO` в `catch` рядом с `e.printStackTrace();` и добавим номер задачи, вроде такого:
```
// TODO (Card #50): find better approach for exceptions logging
```

2016-11-09 09:29 UTC, kevromster commented on src/main/java/edu/xored/tracker/UserController.java
> +        try (BufferedReader inStream = new BufferedReader(new InputStreamReader( theProcess.getInputStream() ))) {
а зачем тут дополнительные пробелы внутри скобок `()`? кажется, не нужны

2016-11-09 09:29 UTC, kevromster commented on src/main/java/edu/xored/tracker/UserController.java
> +    private class ReceiveOutputException extends RuntimeException {
давай назовём его `ExecutionFailedException`, и reason напишем вроде "ошибка выполнения команды"

2016-11-09 09:40 UTC, Declow0 commented on src/main/java/edu/xored/tracker/UserController.java
> +    private static String getNameCommand = "git config user.name";
Done.

2016-11-09 09:40 UTC, Declow0 commented on src/main/java/edu/xored/tracker/UserController.java
> +    String getOutput (String command) {
Done.

2016-11-09 09:40 UTC, Declow0 commented on src/main/java/edu/xored/tracker/UserController.java
> +        // TODO: How to work with exceptions? How to log them?
Done.

2016-11-09 09:40 UTC, Declow0 commented on src/main/java/edu/xored/tracker/UserController.java
> +        try (BufferedReader inStream = new BufferedReader(new InputStreamReader( theProcess.getInputStream() ))) {
Done.

2016-11-09 09:40 UTC, Declow0 commented on src/main/java/edu/xored/tracker/UserController.java
> +    private class ReceiveOutputException extends RuntimeException {
Done.

2016-11-09 09:46 UTC, kevromster requested changes

2016-11-09 09:46 UTC, kevromster commented on src/main/java/edu/xored/tracker/UserController.java
> +    private String getOutput (String command) {
Обычно private-методы после public идут. Надо будет это в style guide прописать. Давай передвинем. Остальное всё ок.

2016-11-09 09:55 UTC, Declow0 commented on src/main/java/edu/xored/tracker/UserController.java
> +    private String getOutput (String command) {
Done.

2016-11-09 09:56 UTC, kevromster approved these changes

2016-11-09 09:56 UTC, merged