Как разработчик хочу coding style документ для AngularJS (Doc/41)
edu-xored/tracker-web pull request #34
Opened 2016-11-12 21:29 UTC by Astronautr

Добавил небольшой style guide для AngularJS. Он должен помочь писать код для фронтенда в одном стиле всей команде, а также избежать недочётов (неверно выставленные отступы) при оформлении и написании кода.

2016-11-12 21:29 UTC, Astronautr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как разработчик хочу coding style документ для AngularJS, чтобы все остальные колбасили нормальный код](https://trello.com/c/FXZFthBN/41-coding-style-angularjs)

2016-11-13 04:31 UTC, kevromster requested changes

2016-11-13 04:31 UTC, kevromster commented on doc/AngularJS_STYLE_GUIDE.md
> +Пример именования файлов:
не только файлов, а, судя по примерам, различных сущностей

2016-11-13 04:31 UTC, kevromster commented on doc/AngularJS_STYLE_GUIDE.md
> +SomeController(){
ты ниже пишешь про пробел перед скобкой `{`, а тут его нет

2016-11-13 04:31 UTC, kevromster commented on doc/AngularJS_STYLE_GUIDE.md
> +    method    :    'POST',
тут отступ пробелом, а должно быть табом

2016-11-13 05:05 UTC, artsaban submitted a review, later dismissed

2016-11-13 05:05 UTC, whyme7 commented on AngularJS_STYLE_GUIDE.md
> +В прошлом секции можно было заметить что каждому компоненту соответствует отдельный файл, что и является рекомендуемой практикой для данного проекта.
Очепятка

2016-11-13 05:15 UTC, whyme7 commented on AngularJS_STYLE_GUIDE.md
> +* Выносите логику из контроллеров, делегируя её сервисам и фабрика.
Тут окончание забыл у фабрик :)

2016-11-13 05:28 UTC, artsaban requested changes

2016-11-13 05:28 UTC, whyme7 commented on doc/AngularJS_STYLE_GUIDE.md
> +* Выносите логику из контроллеров, делегируя её сервисам и фабрика.
Забыл окончание у фабрик :)

2016-11-13 05:28 UTC, whyme7 commented on doc/AngularJS_STYLE_GUIDE.md
> +В прошлом секции можно было заметить что каждому компоненту соответствует отдельный файл, что и является рекомендуемой практикой для данного проекта.
Очепятка.

2016-11-13 05:48 UTC, astronautr commented on doc/AngularJS_STYLE_GUIDE.md
> +Пример именования файлов:
Done.

2016-11-13 05:49 UTC, Astronautr commented on doc/AngularJS_STYLE_GUIDE.md
> +SomeController(){
Done.

2016-11-13 05:49 UTC, Astronautr commented on AngularJS_STYLE_GUIDE.md
> +В прошлом секции можно было заметить что каждому компоненту соответствует отдельный файл, что и является рекомендуемой практикой для данного проекта.
Done.

2016-11-13 05:49 UTC, Astronautr commented on doc/AngularJS_STYLE_GUIDE.md
> +В прошлом секции можно было заметить что каждому компоненту соответствует отдельный файл, что и является рекомендуемой практикой для данного проекта.
Done

2016-11-13 05:49 UTC, astronautr commented on doc/AngularJS_STYLE_GUIDE.md
> +* Выносите логику из контроллеров, делегируя её сервисам и фабрика.
Done.

2016-11-13 05:51 UTC, Astronautr commented on doc/AngularJS_STYLE_GUIDE.md
> +    method    :    'POST',
Хм, забавно что редактируя этот файл в редакторе от Github, я вижу символы табуляции, а на сайте они превращаются в пробелы. Возможно, дело в том, что я скопипастил из исходников лежащих на сайте. Сейчас попробую различные варианты правки.

2016-11-13 05:59 UTC, Astronautr commented on doc/AngularJS_STYLE_GUIDE.md
> +    method    :    'POST',
Исправил. Но сообщение к коммиту вышло кривым - случайно нажал 'Enter' когда редактировал на гитхабе.

2016-11-13 06:09 UTC, artsaban approved these changes

2016-11-13 10:35 UTC, kevromster requested changes

2016-11-13 10:35 UTC, kevromster commented on doc/AngularJS_STYLE_GUIDE.md
> +/* стоит избегать */
Стоит использовать?

2016-11-13 10:35 UTC, kevromster commented on doc/AngularJS_STYLE_GUIDE.md
> +* При форматировании кода внутри тела функций, сервисов и т.д. **обязательно** использовать пробелы, а не табуляцию. Установленными размерами такого форматирования считаются 4 пробела справа и слева
Непонятно, зачем тут отсылка к двоеточию из примера и что такое "установленный размер 4 пробела".
Этот пункт же просто говорит, что внутри строки, когда мы красиво выравниваем код, для выравнивания должны использоваться только пробелы, а табы - только для отступа от края.
Предлагаю переформулировать этот пункт.

2016-11-13 12:22 UTC, Astronautr commented on doc/AngularJS_STYLE_GUIDE.md
> +/* стоит избегать */
Done.

2016-11-13 12:24 UTC, astronautr commented on doc/AngularJS_STYLE_GUIDE.md
> +* При форматировании кода внутри тела функций, сервисов и т.д. **обязательно** использовать пробелы, а не табуляцию. Установленными размерами такого форматирования считаются 4 пробела справа и слева
Убрал второе предложение - оно лишь путает. Первое передаёт посыл, суть которого - форматирование пробелами происходит только внутри строки.

2016-11-14 03:34 UTC, kevromster approved these changes

2016-11-14 11:49 UTC, Declow0 commented on doc/AngularJS_STYLE_GUIDE.md
> +	**Важно**: всегда стоит убеждаться что используемый Вами редактор использует именно символ табуляции, а не заменяет его несколькими пробелами.
Вообще "убеждаться, что". Предыдущая строчка противоречит этой. Если табуляция 4 пробела, то это 4 пробела и никакого символа табуляции нет.

2016-11-14 11:49 UTC, Declow0 commented on doc/AngularJS_STYLE_GUIDE.md
> +* При форматировании кода внутри тела функций, сервисов и т.д. **обязательно** использовать пробелы, а не табуляцию.
Что это значит? Если не будет табуляции все съедет.

2016-11-14 11:49 UTC, Declow0 commented on doc/AngularJS_STYLE_GUIDE.md
> +Стоит отметить, что закрывающая скобка для выражения подобного рода (объявленя функций, условные операторы, циклы и т.д.) не выделяется символом `;`.
объявленя функций - опечатка

2016-11-14 11:55 UTC, Astronautr commented on doc/AngularJS_STYLE_GUIDE.md
> +	**Важно**: всегда стоит убеждаться что используемый Вами редактор использует именно символ табуляции, а не заменяет его несколькими пробелами.
Ок, запятую правлю. Но я говорил про символ табуляции **равный по длине** четырём символам пробела, а не просто равный им.

2016-11-14 11:57 UTC, Declow0 commented on doc/AngularJS_STYLE_GUIDE.md
> +	**Важно**: всегда стоит убеждаться что используемый Вами редактор использует именно символ табуляции, а не заменяет его несколькими пробелами.
А ты посмотри в обычном редакторе, что есть табуляция на самом деле. )

2016-11-14 12:01 UTC, astronautr commented on doc/AngularJS_STYLE_GUIDE.md
> +* При форматировании кода внутри тела функций, сервисов и т.д. **обязательно** использовать пробелы, а не табуляцию.
@Declow0 Именно, без табуляции всё поедет - потому тут речь про пробелы. Тут говорится, что если мы форматируем не отсуп содержимого строки от левого края, то используем пробелы вместо табуляции. Может и правда стоит переформулировать, подумаю. Можешь глянуть на исходник примера - там табуляция для отступа от края, а пробелы для форматирования всего, что дальше табуляции.

2016-11-14 12:04 UTC, Astronautr commented on doc/AngularJS_STYLE_GUIDE.md
> +Стоит отметить, что закрывающая скобка для выражения подобного рода (объявленя функций, условные операторы, циклы и т.д.) не выделяется символом `;`.
Done.

2016-11-14 12:05 UTC, astronautr commented on doc/AngularJS_STYLE_GUIDE.md
> +	**Важно**: всегда стоит убеждаться что используемый Вами редактор использует именно символ табуляции, а не заменяет его несколькими пробелами.
Done.

2016-11-14 13:45 UTC, Declow0 approved these changes

2016-11-14 13:45 UTC, artsaban approved these changes

2016-11-14 13:46 UTC, mgtriffid approved these changes

2016-11-15 15:16 UTC, pleshkovvli approved these changes

2016-11-17 04:13 UTC, merged