Add files upload/download (Feature/40)
edu-xored/tracker-web pull request #35
Opened 2016-11-14 16:24 UTC by pleshkovvli

2016-11-14 16:26 UTC, pleshkovvli commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как разраб фронтенда, хочу эндпойнты для прикрепления файликов, чтобы мог разрабатывать клиентскую часть для этого](https://trello.com/c/f30AJUi8/40--)

2016-11-14 16:39 UTC, mgtriffid submitted a review, later dismissed

2016-11-14 16:39 UTC, mgtriffid commented on src/main/java/edu/xored/tracker/FileService.java
> +    public ResponseEntity<byte[]> getFile(long hash, String name) throws IOException {
Мне кажется, служба, которая `@Service`, не должна знать ничего о Response, Request и прочем HTTP. Как насчёт вынести это вверх, в контроллер, а в сигнатурах службы оставить только InputStream?

2016-11-14 16:39 UTC, mgtriffid commented on src/main/java/edu/xored/tracker/FileService.java
> +                return "File already exist";
Почему бы не обработать исключительные ситуации исключениями?

2016-11-15 02:15 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/FileService.java
> +    public ResponseEntity<byte[]> getFile(long hash, String name) throws IOException {
А исключения тогда тоже без ResponseStatus делать?

2016-11-15 11:47 UTC, kevromster requested changes

2016-11-15 11:47 UTC, kevromster commented on src/main/java/edu/xored/tracker/FileService.java
> +        try {
зачем этот `try`, пусть кидает все возникающие IOException наверх

2016-11-15 11:47 UTC, kevromster commented on src/main/java/edu/xored/tracker/FileService.java
> +            String path = "./files/" + String.valueOf(hash);
Здесь _files_ - это некая общая папка, где мы будем хранить весь аплоад для всех ишуёв, пока git-core нам не даст API для засовывания этого добра в git-репозиторий, так?
Давай её имя вынесем в отдельную константу вроде `private static final String ATTACHEMENTS_ROOT_DIR = "./files";`.
Ну и где-то в этом классе должен быть написан комментарий в духе `// TODO: store attachements via git core API.`

2016-11-15 11:47 UTC, kevromster commented on src/main/java/edu/xored/tracker/FileService.java
> +            BufferedOutputStream stream =
Этот stream лучше через try-with-resources инициализировать, google it

2016-11-15 11:47 UTC, kevromster commented on src/main/java/edu/xored/tracker/FileService.java
> +    public String saveFile(long hash, MultipartFile file) {
1) String не надо возвращать. Тут ничего возвращать не нужно - либо вылетит эксепшн, либо метод нормально отработает до конца.
2) Предлагаю уточнить терминологию: вместо слишком общего понятия _File_ в имени сервиса и методах использовать понятие _Attachement_.
3) Давай переменную _hash_ переименуем в _issueHash_, иначе сейчас непонятно что за хэш такой передаётся сюда.

2016-11-15 11:47 UTC, kevromster commented on src/main/java/edu/xored/tracker/FileService.java
> +    public ResponseEntity<byte[]> getFile(long hash, String name) throws IOException {
исключения в контроллере - с ResponseStatus можно.

2016-11-15 11:47 UTC, kevromster commented on src/main/java/edu/xored/tracker/FileService.java
> +        } finally {
try-with-resources спасут от finally (заодно можешь погуглить, почему finally в таком виде не лучшая идея)

2016-11-15 11:52 UTC, mgtriffid commented on src/main/java/edu/xored/tracker/FileService.java
> +        try {
Мне кажется, не надо бросать наверх IOException. Я бы предпочел завернуть в своё исключение и бросать уже его. Ибо контроллеру нет дела до кишок файлов. Он пользуется FileService и не особо хочет знать о каком-то IO.

2016-11-15 12:17 UTC, kevromster commented on src/main/java/edu/xored/tracker/FileService.java
> +        try {
да, можно и так

2016-11-16 00:25 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/FileService.java
> +        } finally {
Переделал

2016-11-17 04:53 UTC, kevromster requested changes

2016-11-17 04:53 UTC, kevromster commented on src/main/java/edu/xored/tracker/AttachmentService.java
> +    private static final String ATTACHMENTS_ROOT_DIR = "./files";
Давай здесь тоже File.separator вместо слэша

2016-11-17 04:53 UTC, kevromster commented on src/main/java/edu/xored/tracker/AttachmentService.java
> +            throw new FileAlreadyExistsException();
Предлагаю тут просто перезаписывать существующий файл. Всё-таки в том же ишуе с тем же именем файла - скорее всего хотим перезаписать.

2016-11-17 04:53 UTC, kevromster commented on src/main/java/edu/xored/tracker/AttachmentService.java
> +    private class StreamErrorException extends RuntimeException {
Предлагаю назвать его `public static class AttachementException`. При его выбросе указывать исходный _IOException_ как cause (посмотри имеющиеся конструкторы у _Exception_).

2016-11-17 04:53 UTC, kevromster commented on src/main/java/edu/xored/tracker/AttachmentService.java
> +    private class FileIsEmptyException extends RuntimeException {
Пусть он наследуется от _AttachementException_ (см. ниже), ну и тоже public static будет.

2016-11-17 04:53 UTC, kevromster commented on src/main/java/edu/xored/tracker/AttachmentService.java
> +        String path = ATTACHMENTS_ROOT_DIR + File.separator + String.valueOf(issueHash);
Здесь копипаста кода - аналогичным образом получаем _path_ в get-методе. Давай вынесем в отдельный метод. Вообще, посмотри на классы _Path_/_Paths_, которые позволяют конструировать пути без явной конкатенации строк и заморочек с сепаратором.

2016-11-17 04:53 UTC, kevromster commented on src/main/java/edu/xored/tracker/AttachmentService.java
> +    private class FileAlreadyExistsException extends RuntimeException {
этот, соответственно, не нужен

2016-11-17 04:53 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueController.java
> +import java.io.IOException;
не увидел, зачем оно тут нужно

2016-11-17 04:53 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueController.java
> +    @Autowired(required = false)
а почему/зачем `required = false`?

2016-11-17 04:53 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueController.java
> +        return "Success!";
может, тут что-то другое вместо строки возвращать?

2016-11-17 04:54 UTC, kevromster commented
Общее замечание - commit messages оформлены неправильно - нет ссылки на номер задачи.

2016-11-17 15:53 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/AttachmentService.java
> +            throw new FileAlreadyExistsException();
Может сделать варианты - перезаписать или новый файл?

2016-11-17 16:46 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/AttachmentService.java
> +    private static final String ATTACHMENTS_ROOT_DIR = "./files";
Сделал все пути через Path

2016-11-17 16:46 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/AttachmentService.java
> +        String path = ATTACHMENTS_ROOT_DIR + File.separator + String.valueOf(issueHash);
Сделал

2016-11-17 16:46 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/AttachmentService.java
> +            throw new FileAlreadyExistsException();
Пока убрал выброс исключения

2016-11-17 16:46 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/AttachmentService.java
> +    private class FileIsEmptyException extends RuntimeException {
Сделал

2016-11-17 16:46 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/AttachmentService.java
> +    private class FileAlreadyExistsException extends RuntimeException {
Убрал

2016-11-17 16:47 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/AttachmentService.java
> +    private class StreamErrorException extends RuntimeException {
Сделал

2016-11-17 16:47 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/IssueController.java
> +import java.io.IOException;
Убрал

2016-11-17 16:47 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/IssueController.java
> +    @Autowired(required = false)
Убрал

2016-11-17 16:48 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/IssueController.java
> +        return "Success!";
Заменил на ResponseEntity<String>

2016-11-19 14:15 UTC, kevromster requested changes

2016-11-19 14:15 UTC, kevromster commented on src/main/java/edu/xored/tracker/AttachmentService.java
> +    private Path getIssuePath (long issueHash) {
давай private-методы после public размещать, перенесём его вниз

2016-11-19 14:15 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueController.java
> +    @RequestMapping(value="/{hash}/upload", method=RequestMethod.POST)
@PostMapping по аналогии с остальными endpoints

2016-11-19 14:15 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueController.java
> +    @RequestMapping(value="/{hash}/download", method=RequestMethod.GET)
@GetMapping?

2016-11-19 14:15 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueController.java
> +        return new ResponseEntity<byte[]>(bytes, headers, HttpStatus.CREATED);
Стоит погуглить как правильно возвращать файлы - вряд ли это массив байт, скорее _InputStreamResource_ или что-то вроде того.

В остальном код выглядит ОК.

2016-11-19 17:45 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/AttachmentService.java
> +    private Path getIssuePath (long issueHash) {
Сделал

2016-11-19 17:45 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/IssueController.java
> +    @RequestMapping(value="/{hash}/upload", method=RequestMethod.POST)
Сделал

2016-11-19 17:45 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/IssueController.java
> +    @RequestMapping(value="/{hash}/download", method=RequestMethod.GET)
Сделал

2016-11-20 02:53 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/IssueController.java
> +        return new ResponseEntity<byte[]>(bytes, headers, HttpStatus.CREATED);
Сделал, но не уверен, что это лучшее решение

2016-11-20 12:15 UTC, Astronautr commented on src/main/java/edu/xored/tracker/AttachmentService.java
> +            int data = 0;
`data` можно не инициализировать значением при объявлении.

2016-11-20 12:18 UTC, astronautr requested changes

2016-11-20 12:18 UTC, Astronautr commented on src/main/java/edu/xored/tracker/AttachmentService.java
> +    public void saveAttachment(long issueHash, MultipartFile file) {
Мне кажется, стоит изменить имена методов сервиса на что-то типа `uploadAttachment` и `downloadAttachment`. Это добавит каплю прозрачности (но тут ИМХО, так что не обязательно).

2016-11-20 12:20 UTC, astronautr requested changes

2016-11-20 12:20 UTC, Astronautr commented on src/main/java/edu/xored/tracker/AttachmentService.java
> +            int data = 0;
`data` можно не инийиализировать нулём при объявлелнии - значение всё равно будет присвоено позже.

2016-11-20 12:33 UTC, astronautr requested changes

2016-11-20 12:33 UTC, Astronautr commented on src/main/java/edu/xored/tracker/IssueController.java
> +            return new ResponseEntity<InputStreamResource>(out, headers, HttpStatus.CREATED);
На счёт того как возвращать файл: было бы клёво, если по запросу вида (в данной ветке ещё нет префикса /api для endpoint'ов) `localhost:8080/issues/{issueHash}/download?name=<fileName>` инициализировался стандартный (для браузера) диалог сохранения файла. Идеи реализации такого функционала есть, например, [здесь](http://memorynotfound.com/spring-mvc-download-file-examples/). Там описаны различные варианты, из которых следует что сам метод в `IssueController` может возвращать как и `void`, так и `Resource`, etc.

Предлагаю, либо пройтись по вариантам в статье и сразу адаптировать всё сделать по красоте, либо, если первый вариант занимает много времени и есть уверенность что на фронтенде можно разобраться с `InputStreamResource`, то оставить в текущем виде.

2016-11-20 13:45 UTC, kevromster commented on src/main/java/edu/xored/tracker/AttachmentService.java
> +    public void saveAttachment(long issueHash, MultipartFile file) {
тогда уж просто upload/download, хотя мне и как сейчас нравится - имхо, можно оставить как есть.

2016-11-20 13:55 UTC, kevromster approved these changes
LGTM

2016-11-20 13:55 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueController.java
> +            return new ResponseEntity<InputStreamResource>(out, headers, HttpStatus.CREATED);
Предлагаю это оставить на frontend-задачу, а тут оставить пока как есть, чтобы сейчас не зависать.

2016-11-21 15:28 UTC, astronautr approved these changes
LGTM

2016-11-22 19:32 UTC, Declow0 approved these changes

2016-11-23 05:34 UTC, merged