Add in-memory repositories for Issue (feature/8)
edu-xored/tracker-web pull request #36
Opened 2016-11-22 16:01 UTC by zaNudda

Card: #8

2016-11-22 16:02 UTC, zaNudda commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +        return issuesMap.replace(hash, issue);
Сейчас возвращается значение issue до изменения (стандартное поведение метода Map.replace()). Это корректно, или логичнее возвращать изменённое значение?

2016-11-22 16:02 UTC, usukololgubu commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +        issuesMap.remove(issueId);
Сейчас не возвращается ничего, стоит ли возвращать удалённую issue?

2016-11-22 16:03 UTC, zaNudda commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как разраб бэкенда, хочу временные in-memory службы data layer вместо настоящих, использующих cli core](https://trello.com/c/ZovYNW8x/8-in-memory-data-layer-cli-core)

2016-11-22 16:20 UTC, zaNudda commented
Если кто-то использует [Insomnia](https://insomnia.rest/), то вот [тут](https://gist.github.com/zaNudda/a25df4ac13e3e9bd98f32243472edf4a) минимальный набор запросов.

2016-11-23 05:51 UTC, kevromster requested changes

2016-11-23 05:51 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueRepository.java
> +}
пустая строка в конце

2016-11-23 05:51 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueController.java
> +    private IssueRepository issueRepository = new IssueRepositoryImpl();
Лучше `@Autowired` вместо явного указания реализации тут. И сам _IssueRepository_ можно `@Service`'ом сделать, аналогично _AttachementService_.

2016-11-23 05:51 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +        issuesMap.remove(issueId);
не думаю, что сейчас это нужно

2016-11-23 05:51 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +public class IssueRepositoryImpl implements IssueRepository {
предлагаю всё-таки не Impl, а какое-то более говорящее название придумать. Хотя бы _InMemoryIssueRepository_.

2016-11-23 05:51 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +    public <S extends Issue> S save(S issue) {
Как good practice, очень рекомендую на все переопределяемые методы добавлять анотацию `@Override` - очень помогает в понимании кода. Давай везде её поставим.

2016-11-23 05:51 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueRepository.java
> +    <S extends Issue> S replace(Long hash, S issue);
Раз это интерфейс, давай на все методы (и на сам интерфейс заодно) добавим javadoc-описание. В духе:
```
/**
 * Replaces issue with the given hash by a new one.
 * @hash здесь описание параметра
 * @issue здесь описание параметра
 * @return the original issue that were replaced
*/
```

2016-11-23 05:51 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +        return issuesMap.replace(hash, issue);
Да, это корректно. И это лучше описать в javadoc'е интерфейса.

2016-11-23 05:51 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +}
пустая строчка в конце файла.

2016-11-23 09:46 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +        return issuesMap.size();
Разве здесь не нужно возвращать хэш ишуя?

2016-11-24 03:53 UTC, kevromster requested changes

2016-11-24 03:53 UTC, kevromster commented on pom.xml
> +      <artifactId>spring-data-jpa</artifactId>
а зачем это нужно?

2016-11-24 03:53 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueController.java
> +        //assertIssueExists(hash);
зачем закомментил?

2016-11-24 03:53 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueController.java
> +        //assertIssueExists(hash);
зачем закомментил?

2016-11-24 03:53 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueController.java
> +        System.out.println(status);
дебаг-код не нужен

2016-11-24 03:53 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueRepository.java
> +}
пустая строка в конце

2016-11-24 03:53 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +            outStream.write("I");
зачем мучиться с _vi_, у _git bug new_ есть же опция _-m_, чтобы сразу с командной строки всё передать

2016-11-24 03:53 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +    private static final String bugResolve = "git bug resolve";
давай эти константы в стиле BUG/BUG_NEW/BUG_RESOLVE назовём

2016-11-24 03:53 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +}
пустая строка в конце

2016-11-24 07:47 UTC, pleshkovvli commented on pom.xml
> +      <artifactId>spring-data-jpa</artifactId>
Без неё отваливается CrudRepository

2016-11-24 07:47 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/IssueController.java
> +        //assertIssueExists(hash);
Вернул

2016-11-24 07:47 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/IssueController.java
> +        //assertIssueExists(hash);
Вернул

2016-11-24 07:48 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/IssueRepository.java
> +}
Сделал

2016-11-24 07:48 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +}
Сделал

2016-11-24 07:52 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +            outStream.write("I");
C -m пока не получается сделать, вместо description он пишет summary description

2016-11-24 14:25 UTC, kevromster requested changes
В целом - нужно аккуратно всё протестировать, что работает как ожидается.

2016-11-24 14:25 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +            outStream.write("I");
_git bug new -m "summary\ndescription"_ не работает?

2016-11-24 14:25 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueController.java
> +    private IssueRepository issueRepository = new IssueRepositoryImpl();
напоминаю про эту штуку

2016-11-24 14:25 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +            outStream.write("I");
Надо разобраться. Код, который сейчас, будет работать только с vi/vim, а у пользователя может быть свой редактор настроен.

2016-11-24 14:25 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +    private static Map<String, Issue> issuesMap = new HashMap<>();
1) Здесь нужно добавить коммент, зачем эта мапа остаётся. Типа // TODO: remove when git bug would implement all needed commands.
2) Она не статическая тут - на каждый создаваемый репозиторий должна быть своя мапа, static убрать.
3) Раз мы решили её оставить для реализации команд-заглушек, нужно её тогда синхронно обновлять вместе с вызовом git bug команд - чтобы в ней те же копии ишуёв хранились.

2016-11-24 14:25 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +        findOne(hash).addComment(comment);
Здесь нужно написать так, чтобы коммент добавился в ишуй в нашей заглушечной HashMap'е.

2016-11-24 14:25 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +        if (issueId == null) {
здесь (и в других _delete_) кидать _NotImplementedException_ или вроде того

2016-11-24 14:25 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +            if(info.substring(0,5).equals("usage")) {
На будущее - нужно придумать более надёжный способ индексации об ошибке, например по коду возврата (правда, я не уверен, что у них скрипт нормальные коды возврата возвращает).
Если сейчас этот код работает правильно - можно оставить как есть.

2016-11-24 14:25 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +            if(info.substring(8,12).equals("open")) {
На будущее - хардкодед магические константы. И в целом не очень надёжный разбор вывода команды, он ведь может поменяться. Если сейчас этот код работает, можно пока оставить как есть.

2016-11-26 07:34 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +    private static Map<String, Issue> issuesMap = new HashMap<>();
Вроде сделал

2016-11-26 07:35 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +            if(info.substring(8,12).equals("open")) {
Заменил на константы

2016-11-26 07:35 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +            if(info.substring(0,5).equals("usage")) {
Оставил как есть

2016-11-26 07:35 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +        if (issueId == null) {
Сделал

2016-11-26 07:35 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +        findOne(hash).addComment(comment);
Сделал

2016-11-26 10:47 UTC, kevromster approved these changes
Для текущих целей выглядит ок. Далее будем допиливать отдельными задачами.

2016-11-26 10:48 UTC, merged

2016-11-26 10:54 UTC, kevromster commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как разработчик бэкенда, хочу использовать команды "git bug...", реализованные в проекте tracker-core, для получения списка ишуёв и для их модификации.](https://trello.com/c/TVx46GZF/53-git-bug-tracker-core)