Feature/21
edu-xored/tracker-web pull request #4
Opened 2016-10-23 10:09 UTC by whyme7

2016-10-23 10:19 UTC, whyme7 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как разработчику бэкенда, мне необходима сущность Issue, чтобы реализовать для неё endpoints](https://trello.com/c/ET4Fw1tf/21-issue-endpoints)

2016-10-23 13:32 UTC, kevromster commented
Общие замечания по commit messages, на будущее:

- Напоминаю статью: http://chris.beams.io/posts/git-commit/
- "Сhanges in IssueController" и т.п. - плохо, та как непонятно, что за изменения и зачем. Пишем, что действительно сделано в этом коммите. Если надо, добавляем подробный body.
- Ссылку на номер задачи пишем в формате Card: #X (во всех коммитах пропущено двоеточие)

2016-10-23 13:47 UTC, kevromster requested changes

2016-10-23 13:47 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/Issue.java
> +    public Issue() {
Этот конструктор зачем? У нас нет бизнес-понятия "пустой ишуй"

2016-10-23 13:47 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +    private static Map<Long, Issue> issueMap = new HashMap<Long, Issue>();
Напиши здесь комментарий в духе // TODO: temporary issues storage for testing purposes. Remove when implement access to real issues through CLI core.

2016-10-23 13:47 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +
не очень понимаю, зачем здесь пустая строка

2016-10-23 13:47 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +    private static long hashCounter;
эта переменная, кажется, не нужна

2016-10-23 13:47 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +        return ResponseEntity.status(HttpStatus.OK).body(issueMap.get(hash));
Если ишуя нет, всё равно вернёшь OK - непорядок

2016-10-23 13:50 UTC, whyme7 commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/Issue.java
> +    public Issue() {
Если использовать @RequestBody то он вроде как нужен был. Убрать?

2016-10-23 14:07 UTC, whyme7 commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +    private static long hashCounter;
Я ее в конструкторе использую. Хотя можно убрать и просто явно подавать числа типа лонг.

2016-10-23 14:32 UTC, whyme7 commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +        return ResponseEntity.status(HttpStatus.OK).body(issueMap.get(hash));
Done

2016-10-23 14:32 UTC, artsaban commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +
Done

2016-10-23 14:32 UTC, artsaban commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +    private static Map<Long, Issue> issueMap = new HashMap<Long, Issue>();
Done

2016-10-23 19:13 UTC, whyme7 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как разраб фронтенда, хочу GET-эндпойнт для отдельной таски](https://trello.com/c/JYrKqV8W/6-get)

2016-10-24 03:50 UTC, kevromster approved these changes

2016-10-24 04:30 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/Issue.java
> +    enum Status {
Этому `enum` лучше бы быть `public`, а то получается, что из других пакетов можно звать getStatus(), но с этим совершенно ничего нельзя поделать.

2016-10-24 04:30 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +    public ResponseEntity<Issue> get(@PathVariable("hash") long hash) {
А почему бы нам не вернуть просто `Issue` здесь? Имхо `ResponseEntity` не нужно, ведь мы возвращаем `Issue` чисто по смыслу.
Алсо метод лучше назвать `getIssue`, мне кажется. Это будет более говорящее имя.

2016-10-24 04:30 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +@RequestMapping(value = {"/issue", "/issue/{hash}"})
Вот какой-то [гайд по именованию REST путей](http://www.restapitutorial.com/lessons/restfulresourcenaming.html), который советует назвать наш путь `/issues`, а не `/issue`.

2016-10-24 04:30 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +@RequestMapping(value = {"/issue", "/issue/{hash}"})
А зачем два пути? Мне кажется, лучше будет перенести вторую часть на метод `getIssue`, мол, там написать `@GetMapping("/{hash}")`. Потому что вдруг мы в этом же контроллере захотим создать `getAllIssues`, тогда его мы оставим с просто аннотацией `@GetMapping` и будет органично смотреться.

2016-10-24 04:30 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +    public ResponseEntity<Issue> get(@PathVariable("hash") long hash) {
Коммент не на сейчас, а на будущее. Кажется, круто будет делать get не по хэшу, а по taskId. В трелло мы этой радости лишены, а во вменяемых трекерах обычно ссылка просто содержит номер задачи и это кайфово и понятно, и в закладки легко добавить.
Впрочем, так как трекер распределённый, возможно, мы этой радости в принципе лишены. Короче этот коммент скорее мысли вслух, не надо ничего предпринимать сейчас :)

2016-10-24 04:47 UTC, whyme7 commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +    public ResponseEntity<Issue> get(@PathVariable("hash") long hash) {
А если возвращать Issue, то статус при этом можно возвращать?

2016-10-24 04:49 UTC, whyme7 commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +    public ResponseEntity<Issue> get(@PathVariable("hash") long hash) {
Принято :)

2016-10-24 04:56 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +    public ResponseEntity<Issue> get(@PathVariable("hash") long hash) {
а на отсутствующий ишуй просто null вернуть?

2016-10-24 05:05 UTC, whyme7 commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +    public ResponseEntity<Issue> get(@PathVariable("hash") long hash) {
Done

2016-10-24 05:05 UTC, artsaban commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +@RequestMapping(value = {"/issue", "/issue/{hash}"})
Done

2016-10-24 05:05 UTC, artsaban commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +@RequestMapping(value = {"/issue", "/issue/{hash}"})
Done

2016-10-24 05:05 UTC, artsaban commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/Issue.java
> +    enum Status {
Done

2016-10-24 05:10 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +    public ResponseEntity<Issue> get(@PathVariable("hash") long hash) {
@whyme7 , да, статус будет 200 OK если ишью вернётся. 
@kevromster , а вот `null` возвращать не рекомендую. Можно завести `IssueNotFoundException` рядышком, бросить его, а в контроллере объявить метод, аннотированный 

```
@ExceptionHandler(IssueNotFoundException.class)
@ResponseStatus(HttpStatus.NOT_FOUND)
```

, и тогда если твой `getIssue` бросает `IssueNotFoundException`, то клиент получит 404 Not Found.
Описано тут: https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc#errors-and-rest

2016-10-24 05:32 UTC, kevromster requested changes

2016-10-24 05:32 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +            return null;
Нужно сделать как @mgtriffid описал тут https://github.com/edu-xored/tracker-web/pull/4#discussion_r84621630

2016-10-24 06:55 UTC, whyme7 commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +            return null;
Done.

2016-10-24 07:17 UTC, mgtriffid requested changes

2016-10-24 07:17 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +        public IssueNotFoundException() {
Публичный конструктор не нужен, он создаётся по умолчанию. А в остальном порядок.

2016-10-24 07:28 UTC, kevromster approved these changes

2016-10-24 07:34 UTC, mgtriffid requested changes

2016-10-24 07:34 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +    public class IssueNotFoundException extends RuntimeException {
Ой, а зачем исключение публичное? Этого требует Spring? Если сделать `private class`, будет работать? Если будет - давайте так и сделаем, не нужно давать кому попало бросать наше исключение из нашего уютненького контроллера.

2016-10-24 08:30 UTC, whyme7 commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +        public IssueNotFoundException() {
Да, можно и без него. Вроде работает :)
Done.

2016-10-24 08:31 UTC, artsaban commented on backend/tracker-web-app.backend/src/main/java/com/edu/xored/tracker/IssueController.java
> +    public class IssueNotFoundException extends RuntimeException {
Работает. Сделал IssueNotFoundException приватным.
Done.

2016-10-24 08:33 UTC, mgtriffid approved these changes
LGTM

2016-10-24 08:59 UTC, kevromster approved these changes

2016-10-24 09:01 UTC, merged