Fix bug with empty list of issues (bug/66)
edu-xored/tracker-web pull request #41
Opened 2016-11-26 13:52 UTC by Declow0

Card: #66

2016-11-26 13:52 UTC, Declow0 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Когда нет ишуёв, можно листать страницы до бесконечности. Некорректное отображение списка страниц.](https://trello.com/c/b4hK8qBE/66--)

2016-11-26 13:56 UTC, kevromster requested changes

2016-11-26 13:56 UTC, kevromster commented on src/main/resources/static/controllers/allIssuesController.js
> +            if (lastPageNum == -1)
лучше < 0

2016-11-26 21:08 UTC, Declow0 commented on src/main/resources/static/controllers/allIssuesController.js
> +            if (lastPageNum == -1)
Done.

2016-11-27 04:56 UTC, kevromster approved these changes

2016-11-27 04:56 UTC, merged