Add modal dialog for page with specific issue (feature/51)
edu-xored/tracker-web pull request #43
Opened 2016-11-26 16:55 UTC by Astronautr

Добавил модальный диалог для конкретного ишуя - вместо перехода на отдельную страницу открывается диалог, в котором расположено представление нужно страницы. Может использоваться и форм, вызываемых на главной странице проекта.

На момент создания PR является причиной бага: невозможно забукмаркаться страницу.

2016-11-26 17:11 UTC, Astronautr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как пользователь, хочу красивое отображение выбранного ишуя а-ля всплывающий диалог, аналогично тому, как это происходит в Трелло.](https://trello.com/c/TsnzRKJH/51--)

2016-11-27 04:48 UTC, kevromster requested changes
Ещё заметил, что при закрытии диалога в адресной строке браузера остаётся путь до ишуя вместо возврата к главной странице.

2016-11-27 04:48 UTC, kevromster commented on src/main/resources/static/assets/css/modalDialog.css
> +	/*margin:0 auto;*/
тут и далее предлагаю не коммитить закомментаренный код (либо, если всё-таки нужно, снабдить TODO-комментарием)

2016-11-27 04:48 UTC, kevromster commented on src/main/resources/static/assets/css/style.css
> +    /*overflow-y:hidden;*/
аналогично закомментаренный код

2016-11-27 04:48 UTC, kevromster commented on src/main/resources/static/directives/modalDialog.directive.js
> +		restrict: 'E',
Проблема с отступами. Мы, вроде, везде на табы договаривались? ) в этом файле смешанные отступы.

2016-11-27 04:48 UTC, kevromster commented on src/main/resources/static/views/allIssuesView.html
> +</ng-controller>
пустая строка в конце

2016-11-27 05:31 UTC, Astronautr commented on src/main/resources/static/directives/modalDialog.directive.js
> +		restrict: 'E',
Done.

2016-11-27 05:31 UTC, Astronautr commented on src/main/resources/static/views/allIssuesView.html
> +</ng-controller>
Done.

2016-11-27 08:08 UTC, Astronautr commented on src/main/resources/static/assets/css/style.css
> +    /*overflow-y:hidden;*/
Done.

2016-11-27 08:08 UTC, Astronautr commented on src/main/resources/static/assets/css/modalDialog.css
> +	/*margin:0 auto;*/
Done.

2016-11-27 10:22 UTC, kevromster requested changes

2016-11-27 10:22 UTC, kevromster commented on src/main/resources/static/directives/modalDialog.directive.js
> +		/*compile: function compile(temaplateElement, templateAttrs) {
закомментаренный код

2016-11-27 13:58 UTC, kevromster requested changes

2016-11-27 13:58 UTC, kevromster commented on src/main/resources/static/directives/modalDialog.directive.js
> +            scope.dialogStyle = {};
проблема с отступами - намешаны табы и пробелы

2016-11-27 13:58 UTC, kevromster commented on src/main/resources/static/services/modalDialog.service.js
> +    });
пустая строка в конце.
Отступы табами.

2016-11-27 14:16 UTC, Astronautr commented on src/main/resources/static/directives/modalDialog.directive.js
> +            scope.dialogStyle = {};
Done.

2016-11-27 14:16 UTC, Astronautr commented on src/main/resources/static/services/modalDialog.service.js
> +    });
Done.

2016-11-27 14:20 UTC, kevromster approved these changes

2016-11-27 14:20 UTC, merged