Issue's hash is 6 symbols.
edu-xored/tracker-web pull request #45
Opened 2016-11-26 17:14 UTC by Declow0

Card: #60

2016-11-26 17:14 UTC, Declow0 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как пользователь, хочу короткие хэши в таблице всех ишуёв](https://trello.com/c/Yf5AWjip/60--)

2016-11-27 05:21 UTC, kevromster requested changes

2016-11-27 05:21 UTC, kevromster commented on src/main/resources/static/controllers/allIssuesController.js
> +                    issue.hash = issue.hash.substring(0,6);
Решение неверное - сейчас укороченный хэш стал не только в таблице, но и на странице конкретного ишуя, и в адресной строке браузера. Нужно обрезать хэш только для показа в таблице всех ишуёв.

2016-11-27 11:46 UTC, Declow0 commented on src/main/resources/static/controllers/allIssuesController.js
> +                    issue.hash = issue.hash.substring(0,6);
DONE.

2016-11-27 12:21 UTC, kevromster approved these changes

2016-11-27 12:22 UTC, merged