Add New Form (Feature/55)
edu-xored/tracker-web pull request #47
Opened 2016-11-26 21:01 UTC by Declow0

2016-11-26 21:02 UTC, Declow0 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как пользователь, хочу создавать новые ишуи через кнопочку "Add new"](https://trello.com/c/wi404rOF/55-add-new)

2016-11-27 05:15 UTC, kevromster requested changes

2016-11-27 05:15 UTC, kevromster commented on src/main/resources/static/assets/css/style.css
> +.add-new div{
зачем убрал пробел?

2016-11-27 05:15 UTC, kevromster commented on src/main/resources/static/controllers/addNewController.js
> +                    $scope.status = 'Issue added with hash: #' + response.hash.substring(0,6) + '.';
кажется, тут можно полный хэш выводить, без обрезки

2016-11-27 05:15 UTC, kevromster commented on src/main/resources/static/views/addNewView.html
> +</div>
пустая строка в конце

2016-11-27 05:15 UTC, kevromster commented on src/main/resources/static/controllers/allIssuesController.js
> +                $scope.issues.forEach(function (issue) {
не относится к задаче - пул реквест надо создавать от мастер, а не от другой ветки.

2016-11-27 05:15 UTC, kevromster commented on src/main/resources/static/views/addNewView.html
> +        <select ng-model="issue.status" ng-options="item for item in statusVariants" ng-init="issue.status='OPEN'">
Комбо-бокс не нужен - при создании ишуя статус всегда должен быть OPEN.

2016-11-27 12:00 UTC, closed without merging