Bug/65
edu-xored/tracker-web pull request #48
Opened 2016-11-27 08:14 UTC by pleshkovvli

Add order by time of creation on all Issues page

2016-11-27 08:14 UTC, pleshkovvli commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как пользователь, хочу видеть список всех ишуёв отсортированным по дате создания, а не вразнобой как сейчас](https://trello.com/c/dh9gaKUI/65--)

2016-11-27 09:01 UTC, kevromster requested changes

2016-11-27 09:01 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +            info = info.substring(11,31);
Как-то ненадёжно. Я ещё понимаю откусить "Date: " вначале, но дальше, по-хорошему, надо всю строку парсить, а не какую-то жёстко заданную подчасть.
Скрипт _git bug_ для вывода даты использует команду `git log --max-parents=0 --pretty="%aD" "$issue_hash"`, давай заиспользуем для парсинга такой же формат, как эта команда выводит.
Вот тут, кажется, есть ответ как это сделать: http://stackoverflow.com/questions/2458524/parsing-rfc-2822-date-in-java

2016-11-27 09:01 UTC, kevromster commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> -            while(!info.substring(0,6).equals("Status")) {
А это какой-то workaround был для бага с двойными датами, а теперь стал ненужным?

2016-11-27 11:00 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> -            while(!info.substring(0,6).equals("Status")) {
Да

2016-11-27 11:00 UTC, pleshkovvli commented on src/main/java/edu/xored/tracker/IssueRepositoryImpl.java
> +            info = info.substring(11,31);
Исправил

2016-11-27 13:08 UTC, kevromster requested changes

2016-11-27 13:08 UTC, kevromster commented on src/main/resources/static/views/allIssuesView.html
> +        <tr ng-repeat="issue in filtered = (issues | filter: statusFilter | filter:search) | orderBy: 'createdDateTime'
Лучше наоборот сортировать, свежие вверху таблицы. А то сейчас при большом количестве ишуёв неудобно.
Плюс надо перемерджиться с мастером.

2016-11-27 17:23 UTC, pleshkovvli commented on src/main/resources/static/views/allIssuesView.html
> +        <tr ng-repeat="issue in filtered = (issues | filter: statusFilter | filter:search) | orderBy: 'createdDateTime'
Сделал

2016-11-28 05:16 UTC, kevromster approved these changes

2016-11-28 05:16 UTC, merged