Add form for new Issue (feature/55)
edu-xored/tracker-web pull request #50
Opened 2016-11-27 12:10 UTC by Declow0

Card: #55

2016-11-27 12:10 UTC, Declow0 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как пользователь, хочу создавать новые ишуи через кнопочку "Add new"](https://trello.com/c/wi404rOF/55-add-new)

2016-11-27 13:18 UTC, kevromster requested changes
не работает, пишет:
_Status: Enter a comment!_
возможно, на бэкенде что-то не то.

2016-11-27 14:21 UTC, kevromster commented
Плюс нужно показывать через модальное окно, по аналогии с формой для конкретного ишуя.

2016-11-28 05:19 UTC, kevromster approved these changes

2016-11-28 05:19 UTC, merged