Add autoincrease of height of comment form (feature/68)
edu-xored/tracker-web pull request #51
Opened 2016-11-27 12:26 UTC by Astronautr

Additional work: refactor mass of code, cause code of all files related to postComment duplicated in issue view and controller.

2016-11-27 12:27 UTC, Astronautr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как пользователь, хочу чтобы форма отправки комментария подстраивалась под количество текста, которое она содержит и автоматически расширялось/имело скролл.](https://trello.com/c/SyCq1hCv/68--)

2016-11-27 13:24 UTC, kevromster requested changes

2016-11-27 13:24 UTC, kevromster commented on src/main/resources/static/assets/css/postComment.style.css
> +}
пустая строка в конце

2016-11-27 13:36 UTC, kevromster commented
Не очень хорошо работает. Когда я третью строку начинаю писать, высота уменьшается:
![bug_increase_comment](https://cloud.githubusercontent.com/assets/16014197/20648717/12f8317c-b4e1-11e6-9dd8-5d67f4105947.png)
Потом обратно начинает увеличиваться, но некрасиво.
Проблема и в Chrome, и в Firefox.

2016-11-28 13:56 UTC, astronautr commented on src/main/resources/static/assets/css/postComment.style.css
> +}
Done.

2016-11-28 13:59 UTC, kevromster approved these changes

2016-11-28 13:59 UTC, merged