Add limit to Summary/Description columns on allIssues page
edu-xored/tracker-web pull request #52
Opened 2016-11-27 15:50 UTC by pleshkovvli

Card #72

2016-11-27 15:52 UTC, pleshkovvli commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как пользователь, хочу видеть только небольшую часть дескрипшена на странице со всеми ишью](https://trello.com/c/goQsGF3U/72--)

2016-11-28 05:31 UTC, kevromster requested changes

2016-11-28 05:31 UTC, kevromster commented on src/main/resources/static/assets/css/style.css
> +#all-issues-table td {
отступ пустой строкой

2016-11-28 05:31 UTC, kevromster commented on src/main/resources/static/views/allIssuesView.html
> +				<td ng-click="changeIssueDisplay(issue.hash)">{{issue.status}}</td>
Если я кликаю по строке ишуя с длинным дескрипшном, дескрипшн показывается полностью или сворачивается, отлично. Но тогда это должно работать для клика в любой колонке. Однако, при клике в колонке Summary никакого разворота не происходит. Либо доделать, либо убрать этот разворачивающийся функционал.

2016-11-28 05:31 UTC, kevromster commented on src/main/resources/static/controllers/allIssuesController.js
> +        $scope.changeIssueDisplay = function (hash) {
Названия _issueDisplay_/_changeIssueDisplay_ не отражают суть. Нужно что-то более говорящее, например _displayIssueExpanded_/_changeDisplayIssueExpanded_.

2016-11-28 05:31 UTC, kevromster commented
ну и мердж с мастером не забыть

2016-11-28 07:40 UTC, Declow0 commented on src/main/resources/static/assets/css/style.css
> +#all-issues-table td {
Done.

2016-11-28 07:41 UTC, Declow0 commented on src/main/resources/static/views/allIssuesView.html
> +				<td ng-click="changeIssueDisplay(issue.hash)">{{issue.status}}</td>
Done.

2016-11-28 07:41 UTC, Declow0 commented on src/main/resources/static/controllers/allIssuesController.js
> +        $scope.changeIssueDisplay = function (hash) {
Done.

2016-11-28 08:42 UTC, kevromster requested changes
Теперь все столбцы стали одинаковой ширины, и это некрасиво. Остальное работает.

2016-11-28 08:42 UTC, kevromster commented on src/main/resources/static/views/allIssuesView.html
> +                ng-class="{'active': displayIssueExpanded[issue.hash]}"
отступы пробелами

2016-11-28 15:48 UTC, pleshkovvli commented on src/main/resources/static/views/allIssuesView.html
> +                ng-class="{'active': displayIssueExpanded[issue.hash]}"
Убрал

2016-11-28 15:49 UTC, pleshkovvli commented
Добавил разницу

2016-11-28 17:55 UTC, kevromster approved these changes

2016-11-28 17:55 UTC, merged