Add beautiful view of addNewIssue
edu-xored/tracker-web pull request #55
Opened 2016-11-28 12:59 UTC by pleshkovvli

Card #74

2016-11-28 13:51 UTC, kevromster commented
См. скрин, нужно потюнить до большей похожести на макет.
![bug_create_issue_page](https://cloud.githubusercontent.com/assets/16014197/20670558/f8b744da-b5ab-11e6-8393-fe560caee39b.png)
- Уменьшить ширину страницы, как в макете.
- Кнопочку "Create" сделать больше по высоте.
- Снизу "Status:" лучше убрать, а при добавлении ишуя внизу писать строчку "issue created with hash: xxxxx".

2016-11-28 14:57 UTC, pleshkovvli commented
Переделал

2016-11-28 15:03 UTC, kevromster requested changes

2016-11-28 15:03 UTC, kevromster commented on src/main/resources/static/views/addNewView.html
> +.ng-modal-dialog {
а почему не в css?
пробелы с табами напутаны в отступах

2016-11-28 15:06 UTC, kevromster commented
Ещё момент - почему справа расстояние между краем диалога и текстовыми полями больше, чем слева? давай дотянем контролы так, чтобы отступы одинаковыми были

2016-11-28 15:24 UTC, pleshkovvli commented on src/main/resources/static/views/addNewView.html
> +.ng-modal-dialog {
Перегрузка стиля для данного окна; табы исправил

2016-11-28 15:24 UTC, pleshkovvli commented
Вроде симметрично теперь

2016-11-28 17:49 UTC, Declow0 submitted a review, later dismissed
Необходимо поменять шрифты и рамки

2016-11-28 18:00 UTC, kevromster commented
Лучше, чем было до этого, так что к демо зальём. Однако, на больших размерах по-прежнему у меня справа отступ больше и размер самого диалога слишком огромный.

2016-11-29 03:22 UTC, kevromster approved these changes

2016-11-29 03:22 UTC, merged

2016-11-29 03:24 UTC, kevromster commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как пользователь, хочу красивый вид страницы "Create new issue"](https://trello.com/c/Tf41Eqll/74-create-new-issue)