Feature/27
edu-xored/tracker-web pull request #8
Opened 2016-10-24 15:59 UTC by zaNudda

Завести на бэкенде сущность "Комментарий" (Feature #27)

2016-10-25 02:47 UTC, zaNudda commented
![](https://github.trello.services/images/mini-trello-icon.png) [Как разраб бэкенда, хочу сущность "Комментарий".](https://trello.com/c/RkrzKsaW/27--)

2016-10-25 04:37 UTC, mgtriffid requested changes

2016-10-25 04:37 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Comment.java
> +    //endregion Get
Эти комментарии в каком-то языке что-то делают? В Java ими пользоваться не принято, может уберём?

2016-10-25 04:37 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +        comments = new ArrayList<>();
Хмхмхм... Как делать связь на самом деле большой вопрос.
С одной стороны, мы не хотим, чтобы комменты сериализовались в JSON если мы просто просим Issue (как я понимаю), с другой - логично сделать так вот коллекцией. Предлагаю оставить так, а потом если что переделать, когда будет яснее, что нам предоставляет Core. Это типа просто мысли вслух, не нужно реагировать :)

2016-10-25 04:37 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +        return comments;
Этот метод возвращает изменяемую коллекцию, а следующие два предоставляют интерфейс для изменения коллекции. Получается, можно одну и ту же вещь - "добавить коммент" - сделать двумя способами.
Мне кажется, имеет смысл здесь возвращать копию коллекции комментов.

2016-10-25 05:45 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +        comments = new ArrayList<>();
Напрашивается отдельная DTO без комментов. Пока можно забить, да.

2016-10-25 05:47 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +        return comments;
_Collections.unmodifiableCollection()_ чем не пойдёт?

2016-10-25 05:51 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Comment.java
> +    //endregion Get
я за то, чтоб убрать все лишние комменты

2016-10-25 06:08 UTC, kevromster requested changes

2016-10-25 06:08 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Comment.java
> +    public Comment(String author) {
1) Давайте пока уберём дефолт конструктор и вот этот - будем считать невозможным пустой комментарий без контента.
2) Предлагаю следовать правилу "сначала конструкторы, потом public методы" и перенести конструктор выше геттеров-сеттеров.

2016-10-25 06:08 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +    private Issue(){
Не нужен пустой конструктор - прямо в декларации comments напиши  _... = new ArrayList<>();_

2016-10-25 06:08 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +    private Collection<Comment> comments;
Не _Collection_, а _List_ - комментарии упорядочены, и мы об этом знаем.

2016-10-25 06:08 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +        this();
это, соответственно, не нужно

2016-10-25 06:08 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +    public void addComment(Comment comment){
отсутствует пробел перед скобкой {

2016-10-25 06:08 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +    public void addComments(Collection<Comment> comments){
аналогично пробел перед {

2016-10-25 06:08 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +        this.comments.addAll(comments);
нет проверки на comments == null - получишь NPE

2016-10-25 06:19 UTC, zaNudda commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Comment.java
> +    //endregion Get
Вы про регионы? А если мне хочется как-то организовать код и не видеть всю портянку разом? :(
@mgtriffid, @kevromster.

2016-10-25 15:10 UTC, zaNudda commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Comment.java
> +    //endregion Get
Удалено

2016-10-25 15:11 UTC, zaNudda commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +        return comments;
Возвращаю _Collections.unmodifiableCollection()_

2016-10-25 15:11 UTC, zaNudda commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Comment.java
> +    public Comment(String author) {
1. Убрал
1. Ок!

2016-10-25 15:12 UTC, zaNudda commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +    private Collection<Comment> comments;
Поменял

2016-10-25 15:12 UTC, usukololgubu commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +    private Issue(){
Ок, поправил

2016-10-25 15:12 UTC, usukololgubu commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +        this();
@kevromster, тоже убрал

2016-10-25 15:13 UTC, zaNudda commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +    public void addComment(Comment comment){
@kevromster, добавил

2016-10-25 15:13 UTC, zaNudda commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +        this.comments.addAll(comments);
@kevromster, добавил проверку

2016-10-26 04:28 UTC, kevromster requested changes

2016-10-26 04:28 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +    public Collection<Comment> getAllComments() {
давай _List_ возвращать (_unmodifiableList()_)

2016-10-26 04:28 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +        if (comment == null) {
лучше инвертировать условие - получится меньше кода, без лишних return

2016-10-26 04:28 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +        if (comments == null) {
аналогично

2016-10-26 05:47 UTC, mgtriffid commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +    public Collection<Comment> getAllComments() {
А зачем? Чем `List` здесь лучше, чем `Collection`?

2016-10-26 08:05 UTC, kevromster commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +    public Collection<Comment> getAllComments() {
Возвращая List, мы явно специфицируем в контракте, что у нас упорядоченная коллекция

2016-10-26 14:03 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +        if (comment == null) {
Done.

2016-10-26 14:03 UTC, Declow0 commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +        if (comments == null) {
Done.

2016-10-26 15:30 UTC, zaNudda commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +    public Collection<Comment> getAllComments() {
Изменил

2016-10-26 15:31 UTC, zaNudda commented on backend/tracker-web-app.backend/src/main/java/edu/xored/tracker/Issue.java
> +        if (comment == null) {
На мой взгляд вкусовщина, но ок

2016-10-27 02:35 UTC, kevromster approved these changes

2016-10-27 03:22 UTC, mgtriffid approved these changes
LGTM

2016-10-27 03:46 UTC, merged